Display selected gyro header value
betaflight/blackbox-log-viewer pull request #480
Opened 2020-10-29 17:21 UTC by atomgomba

Fixes #479

2020-10-29 17:26 UTC, mikeller submitted a review, later dismissed

2020-10-29 17:26 UTC, atomgomba commented
This is a prepared log file I used to test this

[test-headers.bbl.zip](https://github.com/betaflight/blackbox-log-viewer/files/5460214/test-headers.bbl.zip)

2020-10-31 15:46 UTC, atomgomba commented
Rebased onto master

2020-10-31 17:33 UTC, McGiverGim requested changes

2020-10-31 17:33 UTC, McGiverGim commented on js/flightlog_fielddefs.js
> +
Sonar complains about trailing spaces here...

2020-10-31 17:38 UTC, atomgomba commented on js/flightlog_fielddefs.js
> +
awh, just vscode things. fixed...

2020-10-31 19:07 UTC, McGiverGim approved these changes
Approved. As suggestion for the next time, is good to paste a screen capture of the change. It helps with the review.

2020-10-31 23:26 UTC, mikeller approved these changes

2020-10-31 23:26 UTC, merged