Add debug friendly names depending on versioning
betaflight/blackbox-log-viewer pull request #514
Opened 2021-06-02 09:47 UTC by McGiverGim

This is a better implementation of https://github.com/betaflight/blackbox-log-viewer/pull/506 that maintains backward compatibility when needed.

2021-06-02 11:02 UTC, McGiverGim commented
Sonar complained about tabs not being spaces... I've modified that too, the file is not too big, including lines not modified by me, so this can difficult a little the review. Sorry.

2021-06-02 22:42 UTC, haslinghuis requested changes

2021-06-02 22:42 UTC, haslinghuis commented on js/flightlog_fields_presenter.js
> +            var debugModeName = DEBUG_MODE[flightLog.getSysConfig().debug_mode]; // convert to recognisable name
```suggestion
            const debugModeName = DEBUG_MODE[flightLog.getSysConfig().debug_mode]; // convert to recognisable name
```

2021-06-02 22:42 UTC, haslinghuis commented on js/flightlog_fields_presenter.js
> +            if(fieldName.includes('debug')) {
:space_invader: 
```suggestion
            if (fieldName.includes('debug')) {
```

2021-06-02 22:42 UTC, haslinghuis commented on js/flightlog_fields_presenter.js
> +        DEBUG_FRIENDLY_FIELD_NAMES = {...DEBUG_FRIENDLY_FIELD_NAMES_INITIAL};
Fancy !!!

2021-06-02 22:45 UTC, haslinghuis commented on js/flightlog_fields_presenter.js
> +        if(flightLog) {
```suggestion
        if (flightLog) {
```

2021-06-03 09:08 UTC, McGiverGim commented on js/flightlog_fields_presenter.js
> +            var debugModeName = DEBUG_MODE[flightLog.getSysConfig().debug_mode]; // convert to recognisable name
Done!

2021-06-03 09:09 UTC, McGiverGim commented on js/flightlog_fields_presenter.js
> +        if(flightLog) {
Done!

2021-06-03 09:09 UTC, McGiverGim commented on js/flightlog_fields_presenter.js
> +            if(fieldName.includes('debug')) {
Done!

2021-06-06 23:35 UTC, ctzsnooze approved these changes
This is really fantastic.  Please merge!

2021-06-07 13:10 UTC, mikeller approved these changes

2021-06-07 13:11 UTC, merged