Update  GPS Rescue Altitude, Heading and Tracking, and Altitude, Baro and RTH debugs
betaflight/blackbox-log-viewer pull request #593
Opened 2022-08-29 01:47 UTC by ctzsnooze

Updates or adds the following debug headers and graph configs tp display properly in 4.4.:

- GPS Rescue Altitude
- GPS Rescue Heading
- GPS Rescue Tracking
- GPS Rescue Throttle PID
- RTH
- Altitude
- Barometer

2022-08-29 03:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

2022-08-29 21:42 UTC, haslinghuis requested changes

2022-08-29 21:42 UTC, haslinghuis commented on js/flightlog_fields_presenter.js
> +                            return (value / 100).toFixed(1) + 'm/s';
```suggestion
                            return (value / 100).toFixed(1) + 'm/s';
                        default:
                            return value.toFixed(0);
```

We need an unconditional check in java script.

2022-08-29 21:42 UTC, haslinghuis commented on js/flightlog_fields_presenter.js
> +                            return (value / 10).toFixed(1) + 'deg';
Add a default case here also.

2022-08-29 21:43 UTC, haslinghuis commented
Sonar is really getting picky about changes not touched.

2022-08-31 22:59 UTC, ctzsnooze commented on js/flightlog_fields_presenter.js
> +                            return (value / 10).toFixed(1) + 'deg';
thanks, done

2022-08-31 23:05 UTC, merged