Update Baro debug
betaflight/blackbox-log-viewer pull request #604
Opened 2022-10-21 20:26 UTC by haslinghuis

Updates Baro debug changed in https://github.com/betaflight/betaflight/pull/11911

2022-10-21 21:15 UTC, KarateBrot commented
Dang, that was fast 🚀

2022-10-21 22:21 UTC, KarateBrot requested changes

2022-10-21 22:21 UTC, KarateBrot commented on js/flightlog_fields_presenter.js
> +                            return `${(value / 100).toFixed(0)}`;
```suggestion
                        case 'debug[1]':
                            return `${value.toFixed(0)} hPa`;
                        case 'debug[2]':
                            return `${(value / 100).toFixed(2)} °C`;
                        case 'debug[3]':
                            return `${(value / 100).toFixed(2)} m`;
                        default:
                            return `${(value).toFixed(0)}`;
```

2022-10-21 22:35 UTC, KarateBrot approved these changes

2022-10-22 01:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

2022-10-25 06:54 UTC, blckmn approved these changes

2022-10-25 06:54 UTC, merged