Add GPS DOP debug
betaflight/blackbox-log-viewer pull request #605
Opened 2022-10-24 20:37 UTC by haslinghuis

Adds GPD_DOP debug

https://github.com/betaflight/betaflight/pull/11912

2022-10-24 20:50 UTC, KarateBrot requested changes
Thanks for your work! Can we scale down the displayed DOP values by 100? (1 decimal place)
(They get multiplied by 100 in BF because they are originally float values from ).

2022-10-24 20:50 UTC, KarateBrot commented on js/flightlog_fields_presenter.js
> +                    'debug[3]': 'vDOP (Vertical 1D)',
```suggestion
                    'debug[all]': 'GPS Dilution of Precision',
                    'debug[0]': 'Number of Satellites',
                    'debug[1]': 'pDOP (positional - 3D)',
                    'debug[2]': 'hDOP (horizontal - 2D)',
                    'debug[3]': 'vDOP (vertical - 1D)',
```

2022-10-24 22:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

2022-10-24 22:39 UTC, haslinghuis commented on js/flightlog_fields_presenter.js
> +                    'debug[3]': 'vDOP (Vertical 1D)',
Thanks. Fixed.

2022-10-24 23:18 UTC, KarateBrot requested changes

2022-10-24 23:18 UTC, KarateBrot commented on js/flightlog_fields_presenter.js
> +                    'debug[2]': 'hDOP (positional - 2D)',
```suggestion
                    'debug[2]': 'hDOP (horizontal - 2D)',
```

2022-10-25 02:03 UTC, haslinghuis commented on js/flightlog_fields_presenter.js
> +                    'debug[2]': 'hDOP (positional - 2D)',
Fixed

2022-10-25 02:35 UTC, KarateBrot approved these changes

2022-11-05 00:19 UTC, ctzsnooze approved these changes

2022-11-05 00:22 UTC, merged