Added map with home position / craft position / flight trail #490
betaflight/blackbox-log-viewer pull request #613
Opened 2022-11-30 17:10 UTC by bonchan

This PR resolves #490 
![image](https://user-images.githubusercontent.com/3599906/204861875-6d53b6f1-944a-438b-81b5-6af5ad1cfa58.png)
The map uses gps data to display home position, craft position and flight trail 
It can be configured to show altitude colored trail or single color trail
![image](https://user-images.githubusercontent.com/3599906/204862392-0fa68ee6-6e88-41df-822d-13bd5eceb953.png)

PR open for discussion.

2022-11-30 18:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> FAIL
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

2022-11-30 20:17 UTC, haslinghuis requested changes

2022-11-30 20:17 UTC, haslinghuis commented on yarn-error.log
> +Arguments:
Please add to .gitignore:
```
npm-debug.log*
yarn-debug.log*
yarn-error.log*
```

2022-12-01 02:05 UTC, bonchan commented on yarn-error.log
> +Arguments:
done

2022-12-01 02:30 UTC, haslinghuis submitted a review, later dismissed

2022-12-01 04:21 UTC, haslinghuis approved these changes

2022-12-01 07:40 UTC, merged