Added GPX exporter
betaflight/blackbox-log-viewer pull request #614
Opened 2022-11-30 17:35 UTC by bonchan

GPX files can be imported in google earth pro to show a 3d view of the flight to achieve something like [this](https://www.youtube.com/watch?v=4umx4QRSxHs). 

Instructions [here](https://www.youtube.com/watch?v=dhgQ8aPUq_U)

2022-11-30 20:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

2022-11-30 21:30 UTC, haslinghuis commented on js/webworkers/gpx-export-worker.js
> +    for (var frame of chunk) {
```suggestion
  for (const chunk of event.data.frames) {
    for (const frame of chunk) {
```

2022-11-30 21:33 UTC, haslinghuis commented on js/webworkers/gpx-export-worker.js
> +      // trkpt += `<sat>${numSat}</sat>`;
Are you working on this otherwise leave a comment in source.

2022-12-01 02:08 UTC, bonchan commented on js/webworkers/gpx-export-worker.js
> +    for (var frame of chunk) {
done

2022-12-01 02:19 UTC, haslinghuis commented on js/main.js
> +          }
Missing semicolon ;

2022-12-01 02:20 UTC, haslinghuis submitted a review, later dismissed

2022-12-01 02:27 UTC, bonchan commented on js/main.js
> +          }
done

2022-12-01 02:42 UTC, haslinghuis approved these changes

2022-12-01 03:12 UTC, KarateBrot requested changes

2022-12-01 03:12 UTC, KarateBrot commented on js/gpx-exporter.js
> +};
Missing end of line (LF)

2022-12-01 04:40 UTC, bonchan commented on js/gpx-exporter.js
> +};
done

2022-12-01 04:42 UTC, haslinghuis approved these changes

2022-12-01 07:41 UTC, haslinghuis commented
@bonchan please rebase

2022-12-01 12:37 UTC, McGiverGim approved these changes

2022-12-01 20:48 UTC, haslinghuis commented
Another reference for this awesome function: https://www.youtube.com/watch?v=uBXmUG6JZkc

2022-12-02 00:11 UTC, bonchan commented
> @bonchan please rebase

done!

2022-12-02 02:19 UTC, haslinghuis approved these changes

2022-12-02 02:19 UTC, merged