support angle_controller debug
betaflight/blackbox-log-viewer pull request #620
Opened 2022-12-10 03:57 UTC by ctzsnooze

Support for the new `ANGLE_CONTROLLER` debug from @ChrisRosser.

See firmware PR [#12041](https://github.com/betaflight/betaflight/pull/12041).

2022-12-10 07:11 UTC, sugaarK approved these changes

2022-12-10 13:29 UTC, haslinghuis approved these changes

2022-12-10 15:51 UTC, haslinghuis requested changes
`ANGLE_CONTROLLER` has been renamed to `FEEDFORWARD_ANGLE` in firmware.

Now it's `ANGLE_MODE` :)

2022-12-10 15:51 UTC, haslinghuis commented on js/flightlog_fielddefs.js
> +        "ANGLE_CONTROLLER",
```suggestion
        "ANGLE_FEEDFORWARD",
```

2022-12-10 15:51 UTC, haslinghuis commented on js/flightlog_fields_presenter.js
> +        'ANGLE_CONTROLLER' : {
```suggestion
        'ANGLE_FEEDFORWARD' : {
```

2022-12-10 15:51 UTC, haslinghuis commented on js/flightlog_fields_presenter.js
> +                case 'ANGLE_CONTROLLER':
```suggestion
                case 'ANGLE_FEEDFORWARD':
```

2022-12-10 15:51 UTC, haslinghuis commented on js/graph_config.js
> +                    case 'ANGLE_CONTROLLER':
```suggestion
                    case 'ANGLE_FEEDFORWARD':
```

2023-07-15 18:58 UTC, nerdCopter approved these changes

2023-12-03 14:07 UTC, haslinghuis commented
Superseded by #674

2023-12-03 14:07 UTC, closed without merging