Seekbar more metrics
betaflight/blackbox-log-viewer pull request #635
Opened 2023-03-31 14:29 UTC by VolkerGoeschl

Copy of #634 but now from a feature branch (thanks to @nerdCopter I only moved to git a month ago)
OG description:
This allows showing different metrics in the searchbar for spotting spots of interrest in longer logs easier.
The dropdown to select those is right beside the workspace selection. The chosen mode will survive picking a different log from a file but will get reset to average throttle when loading a new file.
The following modes have been implemented (so far)
Average motor throttle: this is the old behavior
maximum Stick input: highest absolute value of (roll/pitch/yaw) (find snap-moves)
maximum Motor differential: difference of highest and lowest motor output (find fast moves/desyncs - thanks to Zoggbarr for the suggestion)

2023-03-31 16:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

2023-03-31 16:56 UTC, haslinghuis commented on js/flightlog_index.js
> +                for (var j = 0; j < 3; j++) {
```suggestion
                for (let j = 0; j < 3; j++) {
```

2023-03-31 16:57 UTC, haslinghuis commented on js/flightlog_index.js
> +                                        for (var j = 0; j < maxRCFields.length; j++) {
```suggestion
                                        for (let j = 0; j < maxRCFields.length; j++) {
```

2023-03-31 16:58 UTC, haslinghuis commented on js/flightlog_index.js
> +                for (j = 0; j < sourceIndex.maxRC.length; j++) {
```suggestion
                for (let j = 0; j < sourceIndex.maxRC.length; j++) {
```

2023-03-31 16:58 UTC, haslinghuis commented on js/flightlog_index.js
> +                for (j = 0; j < sourceIndex.maxMotorDiff.length; j++) {
```suggestion
                for (let j = 0; j < sourceIndex.maxMotorDiff.length; j++) {
```

2023-03-31 16:59 UTC, haslinghuis commented on js/main.js
> +            var
```suggestion
            let
```

2023-03-31 17:00 UTC, haslinghuis requested changes
Please fix lexical scoping and code smells

2023-03-31 20:34 UTC, haslinghuis commented
More code smells to solve :yum:

2023-04-01 09:25 UTC, haslinghuis approved these changes

2023-04-01 09:52 UTC, VolkerGoeschl commented
Now it seems to be accepted by SonarCloud.
Do I need to squash or rebase to get rid of al those micro-commits?
@haslinghuis thank you for your patience!

2023-04-01 10:26 UTC, haslinghuis commented
We have squash and merge, so all good.

2023-04-04 16:48 UTC, nerdCopter commented
the default window size at launch always pushes this off-view for me.
![image](https://user-images.githubusercontent.com/56646290/229861220-e9bbea00-2aaa-4f70-a255-dbe353e38717.png)

thinking the entire bar needs some auto-flow/sizing work :(  

thoughts @haslinghuis ??

2023-04-04 17:02 UTC, RubberQuads commented
> the default window size at launch always pushes this off-view for me. ![image](https://user-images.githubusercontent.com/56646290/229861220-e9bbea00-2aaa-4f70-a255-dbe353e38717.png)
> 
> thinking the entire bar needs some auto-flow/sizing work :(
> 
> thoughts @haslinghuis ??

I want to put it into the seekbar like it's done in the spectrum analyzer. But I need to get a grasp of how the canvases work before -> can we leave it as is for now and I change it to something better in another PR next week (I'm on vacation right now)?

2023-04-26 13:18 UTC, nerdCopter commented
``[moved selector into the seekbar](https://github.com/betaflight/blackbox-log-viewer/pull/635/commits/2232583ac416fb4832452a71fcbf2b1100446def)`` is very sleek :heart: 

for others to review:
invisible until mouse over 
![image](https://user-images.githubusercontent.com/56646290/234586610-4c9ba012-7388-4848-abc5-e2e777b4ef1c.png)

mouse-over:
![image](https://user-images.githubusercontent.com/56646290/234587267-d7737cfa-8e08-408f-8f75-df27914ee89d.png)

upon modifiy:
![image](https://user-images.githubusercontent.com/56646290/234587455-d3b1b24f-5b0d-4b72-ad9d-bf6057e6d61d.png)

2023-04-26 13:22 UTC, nerdCopter commented
please mark any of the above suggestions resolved if they are indeed resolved.
![image](https://user-images.githubusercontent.com/56646290/234588569-c78fb113-e540-4873-a635-541c8c432ef7.png)

2023-04-26 13:26 UTC, VolkerGoeschl commented on js/flightlog_index.js
> +                                        for (var j = 0; j < maxRCFields.length; j++) {
done

2023-04-26 13:27 UTC, VolkerGoeschl commented on js/flightlog_index.js
> +                for (j = 0; j < sourceIndex.maxMotorDiff.length; j++) {
done

2023-04-26 14:14 UTC, nerdCopter approved these changes

2023-04-26 14:42 UTC, haslinghuis commented on js/main.js
> +        var
Slipped through Sonarcloud bot :)

2023-04-26 14:45 UTC, merged