Remove special charachters from eRPM field
betaflight/blackbox-log-viewer pull request #666
Opened 2023-11-06 18:05 UTC by tbolin

The labels of the RPM fields was changed from `eRPM(/100)` to `eRPM` in 
https://github.com/betaflight/betaflight/pull/13123 . This PR does the same in log viewer to so the RPM fields are once again correctly formatted.

2023-11-06 18:20 UTC, ledvinap approved these changes

2023-11-06 18:34 UTC, haslinghuis commented
Will try again build later (most times these are network errors)

![image](https://github.com/betaflight/blackbox-log-viewer/assets/8344830/27b5c7d2-543d-4755-8214-2fb60e461cd9)

2023-11-06 18:36 UTC, haslinghuis requested changes
Will try again build later (most times these are network errors)

![image](https://github.com/betaflight/blackbox-log-viewer/assets/8344830/27b5c7d2-543d-4755-8214-2fb60e461cd9)

2023-11-06 20:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

2023-11-06 20:47 UTC, nerdCopter approved these changes

2023-11-07 03:31 UTC, haslinghuis approved these changes

2023-11-07 03:36 UTC, merged