Added setting of minimum and maximum values of curves on the graphadded minimum and maximum curves values
betaflight/blackbox-log-viewer pull request #689
Opened 2024-01-18 15:22 UTC by demvlad

Added setting of minimum and maximum values of curves on the graph.
The revision is fully compatible with the previous scaling method.

To use it, you need to:

Open "Configure graphs" dialog box.
Check new "MinMax" checbox on curve settings.
Set required values for minimum and maximum chart values for curve (there are real min max values as default).
You need to input min and max values in primary units as in logfile. You can look it at default min max values in text fields,
Click "Save changes".
This is the most versatile way to configure curves.
If it is necessary to plot some curves along the same axis, then you need to set the same or proportional ranges of values for them.

With unchecked "MinMax" checkbox the curve scaled in the standard way, as before.

There is a first step for improvment of curve scales. It will be improved in the future.
For example, it will be possible to automatically combine several curves on one axis.
![setup](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/07f7597f-08b6-4721-8a92-c5677f2874b5)

2024-01-18 16:16 UTC, demvlad commented
All are puushed good in new PR... This version has issue:  minimum and maximum values of curves for some parameters are limited after reloading charts setup dialog box. This issue will resolve in near time. But i see:  it is posible to input any min max values, and chart works normal, but this values are limited after chart setup panel reopening.

2024-01-18 17:54 UTC, demvlad commented
>  it is posible to input any min max values, and chart works normal, but this values are limited after chart setup panel reopening.

There is more interest behavior today: it is posiable input and save any min max values, but exclude zero. Zero values is rewriten after reload of config dialog box.

2024-01-19 14:00 UTC, nerdCopter commented
> Is it posible to use VSCode for debug of this application? I've seen this at the Betaflight configurator page.

Others may know `vscode`, i cannot answer about it.
However, from `yarn gulp debug` command, you can press `F12` (or right click the UI and choose `Inspect`), then you have all the Chromium debug features. `Console` tab and `Sources` tab plus `Watch` is most useful.

2024-01-19 14:35 UTC, demvlad commented
> This version has issue: minimum and maximum values of curves for some parameters are limited after reloading charts setup dialog box. 


This issue is resolved.

2024-01-19 14:37 UTC, demvlad commented
> > Is it posible to use VSCode for debug of this application? I've seen this at the Betaflight configurator page.
> 
> Others may know `vscode`, i cannot answer about it. However, from `yarn gulp debug` command, you can press `F12` (or right click the UI and choose `Inspect`), then you have all the Chromium debug features. `Console` tab and `Sources` tab plus `Watch` and `Breakpoints` are most useful.

2024-01-19 14:42 UTC, demvlad commented
> > Is it posible to use VSCode for debug of this application? I've seen this at the Betaflight configurator page.
> 
> ..... you can press `F12` (or right click the UI and choose `Inspect`), then you have all the Chromium debug features. `Console` tab and `Sources` tab plus `Watch` and `Breakpoints` are most useful.

Thank's!  
The "F12" is working. I will research this.

2024-01-19 14:42 UTC, nerdCopter commented
please dont close PR and make new identical PR's. please fix the branch and push. the PR systems will update accordingly.  even if you have to "force push".

2024-01-19 14:44 UTC, demvlad commented
> please dont close PR and make new identical PR's. please fix the branch and push. the PR systems will update accordingly. even if you have to "force push".
> 
> otherwise you can set a PR as "draft" until you are ready for review.

Ok!

2024-01-19 14:57 UTC, demvlad commented
> please dont close PR and make new identical PR's. please fix the branch and push. the PR systems will update accordingly. even if you have to "force push".

Have i create new PR now?

2024-01-19 14:59 UTC, nerdCopter commented
> > please dont close PR and make new identical PR's. please fix the branch and push. the PR systems will update accordingly. even if you have to "force push".
> 
> Have i create new PR now?

no, just `git push`.  or if error, `git push --force`.

2024-01-19 15:07 UTC, demvlad commented
I've pushed branch after resolving issue.
Do i fix it after that? If yes, how can i fix?

2024-01-19 15:12 UTC, nerdCopter commented
if `fb342b3c` is the last commit, then nothing to do. devs can review now.

2024-01-19 15:19 UTC, demvlad commented
> if `fb342b3c` is the last commit, then nothing to do. devs can review now.

Yes, this is my last commit. Can i do anything else now?

2024-01-19 15:37 UTC, nerdCopter commented
findings:
- if i checkmark min/max without changing the value, the trace will move. uncheck will return.
- if i change the min or max values, there is no way to reset to default values unless a press a number key to reload my workspace. if i were to save a workspace with modified values, how to reset to default values?

2024-01-19 15:53 UTC, demvlad commented
> findings:
> 
> * if i checkmark min/max without changing the value, the trace will move. uncheck will return.
> * if i change the min or max values, there is no way to reset to default values unless a press a number key to reload my workspace. if i were to save a workspace with modified values, how to reset to default values?

Yes, i thought about restoring of defaults values.
Will think how to do that...

2024-01-19 16:46 UTC, demvlad commented
> if `fb342b3c` is the last commit, then nothing to do. devs can review now.

Can i push some new commits to origin while review process?

2024-01-19 16:54 UTC, nerdCopter commented
> Can i push some new commits to origin while review process?

yes

2024-01-19 17:29 UTC, demvlad commented
> findings:
> 
how to reset to default values?

I think to do that by double mouse ckick  into empty input field.

2024-01-19 18:48 UTC, ctzsnooze commented
I think this is looking really good, and I commend what you've achieved.  Hopefully the comments here are encouraging, because it will be very useful when complete.

One thing to consider is things like the motors tab, where there are existing mechanisms to set default min and max.  There is a percentage zoom that zooms in around the middle 50%.  I think it would be a big job, but it would be great if things like motors would somehow automatically end up with a min-max range of 0-100 by default.

Likewise in many debugs the range for values within the debug is defined either in a 0-N range, which 'zooms' in and out around N/2, or in a -N to +N range, which zooms around zero.  If not defined, the range is min-max of the values in the variable (very not nice).

It would be a big job but once this method is in place, I would be willing to go through the min and max configurations for those debugs.  It would certainly simplify things if we only had to set min and max values :-)

2024-01-19 19:22 UTC, demvlad commented
> It would be a big job but once this method is in place, I would be willing to go through the min and max configurations for those debugs. It would certainly simplify things if we only had to set min and max values :-)

Thank you for review!
I have thought about this too. Some parameters has different units into log file and on the charts. I will think how to do recalculation of this units. Must be: what units we see on the chart, same we input into min max fields

2024-01-20 11:05 UTC, demvlad commented
My plans, from easy to hardly:
1. Do restoring default minmax values in fields dialog box.
2. Recalculate units min max values between log and graph units.
3. Do chart refresh after check/uncheck enabled minmax checkbox.

2024-01-23 17:08 UTC, nerdCopter commented
- not resetting to defaults with mouse-click in Linux, did not check Windows

2024-01-23 17:13 UTC, demvlad commented
> My plans, from easy to hardly:
> 
> 1. Do restoring default minmax values in fields dialog box.

Hello!
I have done posible to restore default min max values in fields of dialog box.
You must clear field of input minimum/maximum values and click mouse into it to do that.

2024-01-23 17:37 UTC, nerdCopter commented
`8690e206`
 maybe javascript for Linux mouse-click is different
https://youtu.be/wgm2MUaP0O8

2024-01-23 18:01 UTC, demvlad commented
> * not resetting to defaults with mouse-click in Linux, did not check Windows (or maybe i'm doing it wrong?)

Are you clear input field before click?

2024-01-23 18:07 UTC, demvlad commented
> `8690e206` maybe javascript for Linux mouse-click is different https://youtu.be/wgm2MUaP0O8

You need to completely clear the input field before click.

2024-01-23 19:04 UTC, nerdCopter commented
> You need to completely clear the input field before click. Mouse click will not work if field contains some letters.. I've done that to save input from random mouse click.

okay. that worked, but such is not intuitive. maybe a double-click, regardless of value set, would make more sense?

2024-01-23 19:08 UTC, demvlad commented
> > You need to completely clear the input field before click. Mouse click will not work if field contains some letters.. I've done that to save input from random mouse click.
> 
> okay. that worked, but such is not intuitive. maybe a double-click, regardless of value set, would make more sense?

I wanted to do that,but i do not see a double-click event in the input object...

2024-01-23 19:19 UTC, nerdCopter commented on js/graph_config_dialog.js
> +                $(this).val(GraphConfig.getDefaultCurveForField(flightLog, field.name).MinMax.max);
```suggestion
        $('input[name=MinValue]',elem).dblclick( function() {
                $(this).val(GraphConfig.getDefaultCurveForField(flightLog, field.name).MinMax.min);
        });
        // Add event when mouse click at the clear Maximum input field to restore default Max values.
        $('input[name=MaxValue]',elem).dblclick( function() {
                $(this).val(GraphConfig.getDefaultCurveForField(flightLog, field.name).MinMax.max);
```

2024-01-23 19:20 UTC, nerdCopter commented on js/graph_config_dialog.js
> +                $(this).val(GraphConfig.getDefaultCurveForField(flightLog, field.name).MinMax.max);
https://www.w3schools.com/jquery/event_dblclick.asp
is part of jQuery.

2024-01-23 19:21 UTC, nerdCopter commented
please set your vscode to replace tabs with 4-spaces throughout your new commits.
![image](https://github.com/betaflight/blackbox-log-viewer/assets/56646290/3dbf0039-2e60-4ca4-8ebc-6c25d29ad399)

2024-01-23 19:26 UTC, demvlad commented
dblclick - ok, thank's.
To exchange tab to 4 space - ok. I has used Find-replace tool for it.

2024-01-24 15:29 UTC, nerdCopter commented on js/graph_config_dialog.js
> +                $('input[name=MaxValue]',elem).attr("readonly", !field.curve.EnabledMinMax);
```suggestion
                $('input[name=MaxValue]',elem).attr("readonly", !field.curve.EnabledMinMax);
```

2024-01-24 15:29 UTC, nerdCopter commented on js/graph_config_dialog.js
> +                $('input[name=EnabledMinMax]',elem).attr("checked", (field.curve.EnabledMinMax)? field.curve.EnabledMinMax:false);
```suggestion
                $('input[name=EnabledMinMax]',elem).attr("checked", (field.curve.EnabledMinMax)? field.curve.EnabledMinMax:false);
```

2024-01-24 15:29 UTC, nerdCopter commented on js/graph_config_dialog.js
> +                    $('input[name=MinValue]',elem).val(field.curve.MinMax.min);
```suggestion
                    $('input[name=MinValue]',elem).val(field.curve.MinMax.min);
```

2024-01-24 15:39 UTC, demvlad commented
Updated.
Use double mouse click to restore default min-max field values.

The version with transforming of units min-max values is pushed to separate branch "chart_log_units_conversion".  This is the start version for testing. It wiil be improvment in next time.

2024-01-25 15:06 UTC, nerdCopter commented
- please fix trailing spaces as indicated in above recommendations (you can commit then directly using those `commit suggestions` buttons, then `git pull` those changes to your local copy)
- what are the news changes and how should we test them?

2024-01-25 15:12 UTC, demvlad commented
> My plans, from easy to hardly:
> 
> 2. Recalculate min max values between log and graph units.

I've pushed this impovements.
What units  you see on the charts, similar you see in minmax input fields.
I hope, it will work well..

2024-01-25 16:04 UTC, demvlad commented
> * please fix trailing spaces as indicated in above recommendations (you can commit them directly using those three `commit suggestions` buttons, then `git pull` those changes to your local copy)
> * what are the news changes and how should we test them?

I've change all tab symbols to 4 space in all files which i changed.
I've made big units conversion function to transform values from log units to friendly chart and back. More parameters, more transforms, like in existing function in source code. I hope, i do not take some mistakes in transform. Will be: similar units in charts and min max input fields for all parameters.

2024-01-25 16:06 UTC, nerdCopter commented
the 3 i spoke of are undesired **_trailing_** spaces
![image](https://github.com/betaflight/blackbox-log-viewer/assets/56646290/686fa6fe-465b-4f0c-895d-c4c8d75dff41)

2024-01-25 18:49 UTC, demvlad commented
> the 3 i spoke of are undesired **_trailing_** spaces 

Ok. I have done that. I found how to wiew special symbols in my editor. I will see it in future.
I can not understand before, what is mean your notice :)

2024-01-25 19:24 UTC, demvlad commented
> > findings:
> > 
> > * if i checkmark min/max without changing the value, the trace will move. uncheck will return.


What can i tell about this improvement. I agree, this will be helpfull. But it is not easy matter. There are no mechanismes today to control trace directly from chart setup dialog box (it is a modal window). For example, new trace does not show when we add new curves without configurations save. I will think how to do this, but it may take some time.

2024-01-30 00:39 UTC, ctzsnooze commented
I don't mind if the changes only happen on save.

2024-01-30 03:44 UTC, demvlad commented
> I don't mind if the changes only happen on save.

I'll try to do it later.
I am going to do some service features today:
- fill default minmax values for all curves and for one only.
- auto fit all curves to one similar scale
- add selected curve to other with one similar scale
- add selected curve to other with one zero level.

2024-01-30 14:22 UTC, nerdCopter commented
i have a question, because i don't truly understand the use-case of changing min/max -- would it make more sense to shift or change the "center" (up/down)?  or does modifying the min/max have a needed use? 

@ctzsnooze , thoughts?

2024-01-30 14:54 UTC, demvlad commented
![setup](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/eb006cec-3328-4bbe-a595-f54203f26e82)

Added context menu with service features.
Right mouse click on any min-max control element in chart setup dialog box to show context menu.
Menu comands:
- 'Place all curves at full range' - set all min-max values to default (global min-max values from log file)
- 'Place all curves to one scale' - set min-max values to place all curves in one scale. (By using of previous min-max values what was inputed in fields) 
- 'Place all curves around zero axis' - set min-max values to place all curves around X-axis. (By using of  previous min-max values what was inputed in fields) 
- 'Place this curve at full range' - set min-max values to default for selected curves (which you take the right mouse click)
- 'Fit this curve to one scale at:' - set scale for selected (which you take the right mouse click) to combine it with scale of other curve (selected from next level menu)
- 'Place this curve around zero axis' - set min-max values to place selected (which you take the right mouse click) curve around X-axis.

Many actions use values, which was inputed before. You might look at their changes after menu actions. You might do it many times to get given result.

In future, i want to do posible using of current screen curves min-max values for initialization as addition option(instead of global from log file).

2024-01-30 16:18 UTC, demvlad commented
> i have a question, because i don't truly understand the use-case of changing min/max -- would it make more sense to shift or change the "center" (up/down)? or does modifying the min/max have a needed use?
> 
> @ctzsnooze , thoughts?

Yes, min-max values the most common and universaly way to control the curves, but it is not fast and comfortable. I have done those features to get more fast control. The list of this features may be expanded. But in this version we do not know local min-max values what we look at the screen in current time, therefore we must set it manual...

2024-01-30 18:18 UTC, demvlad commented
> i have a question, because i don't truly understand the use-case of changing min/max -- would it make more sense to shift or change the "center" (up/down)? or does modifying the min/max have a needed use?
> 
> @ctzsnooze , thoughts?

What we can do now:
- place some curves in full range from bottom  to top of chart in same or diferent scales (for example - motors, throttle, current, voltage.)
- place some curves around x axis in same or diffetent scale (for example - control, PIDs signals). But there are some exceptions - stick position - their zero level is 1500. Solve -  manual setting min-max values symmetric around 1500....
That works good for global view, where we know min-max from log.
If i want to view local range of time then i can input min-max values manually.... This is uncomfortable. 
Solve: do pissible to find min-max for current selected range of time.

2024-01-30 19:57 UTC, nerdCopter commented
let's see what others have to say, i think this is coming along nicely!

2024-01-30 20:15 UTC, haslinghuis requested changes

2024-01-30 20:15 UTC, haslinghuis commented on js/flightlog.js
> +
:space_invader:

2024-01-30 20:15 UTC, haslinghuis commented on js/flightlog.js
> +    return  value/100*(this.getSysConfig().maxthrottle - this.getSysConfig().minthrottle) + this.getSysConfig().minthrottle;
:space_invader: give operators space for better readability
```suggestion
    return  value / 100 * (this.getSysConfig().maxthrottle - this.getSysConfig().minthrottle) + this.getSysConfig().minthrottle;
```

2024-01-30 20:15 UTC, haslinghuis commented on js/flightlog.js
> +        motorRaw = value/100*ANALOG_RANGE + MIN_ANALOG_VALUE;
```suggestion
        motorRaw = value / 100 * ANALOG_RANGE + MIN_ANALOG_VALUE;
```

2024-01-30 20:15 UTC, haslinghuis commented on js/flightlog_fields_presenter.js
> +     * @param fieldName Name of the field
Missing flightLog @param

2024-01-30 20:15 UTC, haslinghuis commented on js/flightlog_fields_presenter.js
> +     * @param fieldName Name of the field
Missing @param flightLog

2024-01-30 20:15 UTC, haslinghuis commented on js/graph_config_dialog.js
> +                var option = $('<option></option>')
```suggestion
        const selectColor = $('<select class="color-picker"></select>');
            for (let i = 0; i<GraphConfig.PALETTE.length; i++) {
                const option = $('<option></option>')
```

2024-01-30 20:15 UTC, haslinghuis commented on js/graph_config_dialog.js
> +                var option = $('<option></option>')
```suggestion
        const selectHeight = $('<select class="form-control graph-height"></select>');
            for (let  i = 1;  i<= MAX_HEIGHT; i++) {
                const option = $('<option></option>')
```

2024-01-30 20:15 UTC, haslinghuis commented on js/graph_config_dialog.js
> +                if(field.curve.MinMax!=null) {
```suggestion
                if (field.curve.MinMax != null) {
```

2024-01-30 20:15 UTC, haslinghuis commented on js/graph_config_dialog.js
> +            if(enabled) {
```suggestion
            if (enabled) {
```

2024-01-30 20:15 UTC, haslinghuis commented on js/graph_config_dialog.js
> +                if(fieldName != selected_field_name) {
```suggestion
                if (fieldName != selected_field_name) {
```

2024-01-30 20:15 UTC, haslinghuis commented on js/graph_config_dialog.js
> +                if(enabled) {
```suggestion
                if (enabled) {
```

2024-01-30 20:15 UTC, haslinghuis commented on js/grapher.js
> +                if(field.curve.EnabledMinMax)
```suggestion
                if (field.curve.EnabledMinMax)
```

2024-01-31 06:58 UTC, demvlad commented
I have resolved code style issues and i am pushing it soon.
I see, some min-max values are calculated wrong when i use function from source code. For example - PIDs range is always +-50, SetPoints is +-500. I will research this.

2024-01-31 16:39 UTC, demvlad commented
Please, can someone help me.
I work often at computer without internet.
I make full copy of workspace to it from home PC. All are working. But there are the 5 time of unsuccessfull checking of updates NW.js software in build process.  i spend about 2min for each build.  Is it posible to change gulp file cinfiguration to exclude those checking?

2024-01-31 17:07 UTC, haslinghuis commented
You could download once and copy the cache/0.83.0-sdk folder to the root of your other workspace.

![image](https://github.com/betaflight/blackbox-log-viewer/assets/8344830/53b8bfcf-fc10-4b04-ae0e-d4660fea24e4)

2024-02-01 05:19 UTC, demvlad commented
> You could download once and copy the cache/0.83.0-sdk folder to the root of your other workspace
>

Yes, i have this folder in my workspase. All are working.
But i look at this:
![IMG_20240201_080659_edit_516006987656158](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/546ec52f-fc43-41cb-9918-4372f90c5bfa)

There are 4 time of retrying some checking while build. Their tottal time are 2min.
Is it posible disable those checkings?

2024-02-01 13:01 UTC, haslinghuis commented
Turning off network it starts the same on linux:

```
mark@NUC12WSHi7:~/dev/betaflight/blackbox-log-viewer/test/blackbox-log-viewer$ yarn start
yarn run v1.22.20
warning You don't appear to have an internet connection. Try the --offline flag to use the cache for registry queries.
$ gulp debug
Building for platform(s): linux64.
[13:57:27] Using gulpfile ~/dev/betaflight/blackbox-log-viewer/test/blackbox-log-viewer/gulpfile.js
[13:57:27] Starting 'debug'...
[13:57:27] Starting 'dist'...
warning You don't appear to have an internet connection. Try the --offline flag to use the cache for registry queries.
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
[13:57:27] Finished 'dist' after 351 ms
[13:57:27] Starting 'debug'...
Using v0.83.0 (sdk)
Create cache folder in /home/mark/dev/betaflight/blackbox-log-viewer/test/blackbox-log-viewer/cache/0.83.0-sdk
Using cache for: linux64
```

2024-02-01 15:01 UTC, demvlad commented
> Did you try `yarn --offline start`

Thank you!
This is working on my main PC. Tomorrow will try at other PC

2024-02-02 12:46 UTC, demvlad commented
> Did you try `yarn --offline start`

But seems, it does not work at computer with local network without internet..
Never mind, i found solution:
yarn config set network-timeout 1
The checkings are fast with this setting...

2024-02-02 14:09 UTC, demvlad commented
Branch is updated.
Improvements:
1. Added menu actions for set min-max values for current time interval what we see at window:
    - 'Place all curves at window full range' - for all curves setting
    - 'Place this curve at window full range' - for one selected curve setting
2. Resolve issue wrong min-max values computing for calculated fields (PIDsum, etc)

Short manual.
1. What you want to look at?
   If global view then select 'Place all curves at global full range' menu option.
   If local view in current time then select 'Place all curves at window full range' menu option.
2. If all or many curves must be around X axis - select 'Place all curves around zero axis',
   else use 'Place this curve around zero axis' for one or some curves if they need it.
3. If you need same scale for some curves - select 'Place all curves to one scale' or 'Fit this curve to one scale at:'   

   Note: If you apply 'Place ... around zero axis', then half minmax info is lost.
4. for reset it - return to 1

2024-02-02 15:54 UTC, demvlad commented
I hope, the version with refreshing charts after min-max actions (without press Save button) will be ready on next week.
I tryed, it is possible, but i can do pushing charts setting directly into grapher module...

2024-02-02 16:03 UTC, nerdCopter commented
menu is significantly distant: 
![image](https://github.com/betaflight/blackbox-log-viewer/assets/56646290/a32ea112-9f5a-41e6-9c05-4b015422b999)

new min/max values did not propagate to all graphs until i reloaded my workspace .json.  i suppose it read what was last saved which where larger numbers than this new version.  this is likely not an issue because very few if any people had tested older commits.
compare to above values: 
![image](https://github.com/betaflight/blackbox-log-viewer/assets/56646290/4573497a-9fb8-4b8a-93c8-5c82092e31f0)


seems to be working well.  but i request other devs to test the math/science of it since they may understand the use much better than i.

2024-02-02 16:19 UTC, demvlad commented
> menu is significantly distant: 

That is strange... I see the menu nearly the mouse click. Will think how to check and resolve this..

2024-02-02 16:26 UTC, demvlad commented
> menu is significantly distant: ![image](https://private-user-images.githubusercontent.com/56646290/301900082-a32ea112-9f5a-41e6-9c05-4b015422b999.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4OTA2MjUsIm5iZiI6MTcwNjg5MDMyNSwicGF0aCI6Ii81NjY0NjI5MC8zMDE5MDAwODItYTMyZWExMTItOWY1YS00MWU2LTljMDUtNGIwMTU0MjJiOTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE2MTIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMjY2Y2EyM2JlNTRmOTQyOTAwMzZjN2RmZDM2Y2Y0ZjFjOGYzZjJiMDRhNjlhNTRlYzkxZmIzNmFmNmRmNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rKH4qGRVDN-LB4qaOWo_tNAYETksHYwPyFnZ9xd_WmQ)
> 
> new min/max values did not propagate to all graphs until i reloaded my workspace .json. i suppose it read what was last saved which where larger numbers than this new

Yes, this was olde saved values probably, in log units. I think, in this case should remove all graph, save and create new.

2024-02-02 16:41 UTC, demvlad commented
> > menu is significantly distant:
> 

What operation system do you use?
I will install it to virtual PC for testing.

2024-02-02 17:36 UTC, nerdCopter commented
Linux, Debian 12. XFCE environment.  Dual screen. XFCE handles dual screen as one united display port. 
Last time i tested your PR I was still on old Debian 11 and this did not happen.  
I will test on Ubuntu/XFCE with single screen ... result: same effect.

2024-02-02 18:38 UTC, demvlad commented
>  I will test on Ubuntu 22.04 / XFCE with single screen ... result: same effect.

Ok. Thank's. I will try to test on Ubuntu.

2024-02-02 19:38 UTC, demvlad commented
> Linux, Debian 12. XFCE environment. Dual screen. XFCE handles dual screen as one united display port. Last time i tested your PR I was still on old Debian 11 and this did not happen. I will test on Ubuntu 22.04 / XFCE with single screen ... result: same effect.

I think, i've resolved this issue. Mouses coordinate is changed from screen to client. Now i see more accurate menu position then before.

2024-02-02 21:30 UTC, nerdCopter commented
menu position is proper now :)

2024-02-03 19:07 UTC, demvlad commented
Branch is updated.
Added: charts redrawing after min-max control actions (without press Save button) .

2024-02-03 21:01 UTC, ctzsnooze commented
This is looking better and better!

It is very complicated and you've done a great job.

One UI thing, perhaps when the MinMax checkbox is not enabled, the values for min and max should be grey and not able to be selected?

With the motors traces, the user thinks in terms of 0-100%, but minimal uses raw values.  We transform 48->0 and 2047->100 or something like that. 

The user doesn't want to think about 48 or 2047, they just want percents, so ideally we should allow min and max to be set in the same units that the user sees.  For example, if I know, for instance, that motor values range 0-100%, then if I wanted to look at the 10-40% range, I'd like to enter 10 and 40.  So that's something to think about.

Another query I have is about default values.  At the moment, for motors, the default min and max, if I add a new clean motors trace is -500 to +500.  If I enable Motor 1 with minMax at those values, the motor trace disappears upwards.  If I change another motor trace eg Motor 2 to Motor 1, when I do that, the defaults become 162 and 1719, and that trace appears on-screen.  The only way I can get Motor 1 to look 'correct' (ie the same as the default 0-100 percent is if I enter the range 48-2047 or something like that.

There are quite a lot of things with scaling factors, eg heading is in degrees * 10, and it would be best for the user if the default scale was 0-360, not 0-3600, for instance.  Also for gyro and set point, where the max rate value (I think) sets the scaling of setpoint, which then is used to scale gyro, and gyro_scaled.  

This highlights that there are essentially three MinMax that could be applied as defaults:
- first, -500 to 500, which seems to apply to every trace when first loaded
- second, the user-expected min and max, eg 0-100 for motors, 0-360 for heading, etc.
- third, the minimum and maximum  values of the data in the trace.

At present, we see the first '-500 to 500` range always, on loading the graph.  We get the third option when we re-select the trace in the custom settings dialog.  We don't appear to have a way to get the default range (option 2) at present.

A possible solution is:
- when first loading a new trace, only show -500 to 500 when there is no scaling provided, otherwise show 0-100 for motors, -rateMax to +rateMax for gyro, setpoint, gyro_scaled, etc etc
- when the user changes the trace, using the dropdown, get the actual min and max.

2024-02-03 21:14 UTC, haslinghuis commented
48 or 2047 could like the 1000-2000 range used in motor tab as done in `drivers/dshot.c` in firmware.

2024-02-04 01:04 UTC, ctzsnooze commented
I think its best to fix identified issues here.
It is a huge PR, and requires a lot of work, but I think that respecting the scaling is integral to it being useful.
There are lots of situations where the ranges shown are very different from the raw values, and for those channels, the user-visible values must be used in the min-max fields.

2024-02-04 06:50 UTC, mituritsyn commented
How are the default maximum and minimum values calculated? Shouldn't they be based on the maximum and minimum values of the displayed parameter so that the graph is not cut off?

![image](https://github.com/betaflight/blackbox-log-viewer/assets/15355893/1c8ca7ce-bdef-48b7-b66e-d540e424541e)
![image](https://github.com/betaflight/blackbox-log-viewer/assets/15355893/1387c6ba-b1e5-4d5f-b793-6013c3e53f68)

2024-02-04 07:06 UTC, demvlad commented
Thank all for your reviews and help!
Now we have two separate modes:
- with your presets, when MinMax checkbox is disabled.
-  new extended mode, when it is enabled.
But there are no links between this modes...
I think, now is the time to combine their.
I suggest the next:
- remove MinMax checkbox from users inteeface
- set default min-max values like yours recomended  min-max presets.
- add menu action to restore presets values when this is neсessary.

As result we will be able to:
- use presets minnax values as start
- use really minmax values when it will be necessary.

I will check the values convertor for fields which you write as wrong.

2024-02-04 07:08 UTC, demvlad commented
> How are the default maximum and minimum values calculated? Shouldn't they be based on the maximum and minimum values of the displayed parameter so that the graph is not cut off?
> 

No there are min-max values from log file during the all flight time

2024-02-04 07:45 UTC, mituritsyn commented
> Now there are min-max values from log file during the all flight time. 

Oh I see. By default it use "place at global full range" but with this option graph is clipped and I need to use "place at window full range". Is there some definite logic to this default behaviour?

2024-02-04 08:13 UTC, demvlad commented
> Oh I see. By default it use "place at global full range" but with this option graph is clipped and I need to use "place at window full range". Is there some definite logic to this default behaviour?

What are curves names, which have that behavior? It may be wrong units conversion.

2024-02-04 08:34 UTC, mituritsyn commented
> > Oh I see. By default it use "place at global full range" but with this option graph is clipped and I need to use "place at window full range". Is there some definite logic to this default behaviour?
> 
> What are curves names, which have that behavior? It may be wrong units conversion.

I'm talking about gyro pitch from the screens I've provided. By default they are clipped and max values autodetected around 1900 while they are around 2160. you can see it in second log [here](https://github.com/betaflight/blackbox-log-viewer/files/14156059/pidsfilts.txt)

2024-02-04 09:00 UTC, demvlad commented
> 
I'm talking about gyro pitch from the screens I've provided. By default they are clipped and max values autodetected around 1900 

Ok. Thank's. I will look at this.

2024-02-04 13:12 UTC, demvlad commented
> We might see``
>                     min: 0,
>                     max: 100,
> And if we had something that was supposed to scale equally either side of zero, we just enter:
>                     min: -100,
>                     max: 100,
> Then ditch all the percentage options completely and only use min and max.
>  That's I think the ideal solution, and might simplify coding and the maintenance also.

I true understand,  you suggest to stay that min-max only, and use it to scale cuves at global or local time min-max range?

2024-02-04 18:08 UTC, haslinghuis commented
@demvlad merged #700 - does not seem to conflict - but you would need a rebase

2024-02-04 20:39 UTC, ctzsnooze commented
Thank you, again, for working so much with such a difficult challenge!

You are right, knowing the actual min and max values can be helpful, especially with debugs.  So it would be nice to show those values.  Traditionally, the default behaviour for debugs with undefined graph scaling, has been to scale between min and max.

What needs to happen is that suitable scales should be applied for every debug.  This has not been done, because a lot of debugs got added by people who then didn't worry about the matching blackbox changes.  And then it is difficult for someone else to know what the expected min and max range for some debug values should be; sometimes only the originator of the debug really knows what that range should be.

With a min/max system it will be easier to set suitable defaults, and easier also for the user to modify the scaling to suit their needs.  

If you are able to simplify it, using min / max - and I think you will achieve this -  I'm happy to work through the various debugs and check their scaling.

Once again my heartfelt thanks for your work here.  This is an area that has needed fixing for a long time!  Your idea to show the min and max will help a lot.

2024-02-04 20:45 UTC, ctzsnooze commented
I personally have never liked exponential scaling by default on any curve.

In fact I would make a PR to remove it by default.

The interpretation of the data is much more difficult when exponentially scaled.  None of our data is exponentially considered.  It was intended only to allow visualisation of small value changes around zero, but it confused many users.  I have it turned off always, and it annoys me that I still have to turn it off.

And, as you point out, there is the question, should 'exponential' scaling be done only within the 'defined min/max range' or across the full data point range.  

I think that if we are to retain exponential display, it would be always on the 'displayed' min/max range.  Not the full displayed range.  I guess we should retain this option, for historical reasons, but after your work is done I will make a PR to default it to off on all traces.  For instance now by default it is active on gyro; that's just dumb.  It should not be active on gyro.

2024-02-05 03:38 UTC, demvlad commented
> I personally have never liked exponential scaling by default on any curve.
> In fact I would make a PR to remove it by default.
> 
I set curves expo to zero first, when look at charts. I agree, it can be zero as default and able to change if it is need.

2024-02-05 04:55 UTC, demvlad commented
> As this PR is becoming huge - should we improve in next iteration or here?

I arrange to check and resolve the fields units convertation issues first.
After that, other improvements may be do in next iteration.

2024-02-05 07:42 UTC, demvlad commented
> I'm talking about gyro pitch from the screens I've provided. By default they are clipped and max values autodetected around 1900 while they are around 2160. you can see it in second  log

mituritsyn.
Yes, i have seen this behavior before some time. I've checked, there is some issue in the log statistic data, that i use to set global min-max value. These data is too smaller then real values sometime. I do not know today, why the statistic computing has this behavior. I need to research the source code. But i can resolve this issue quickly. I can use my selfmade function which compute minmax for time interval instead of statistic data. It works well. In your example, if set maximum zoom (fit all time to window) and apply 'Place... at window full range' menu option then all work good.

2024-02-05 09:46 UTC, ctzsnooze commented
@demvlad - hey I found this PR incredibly useful already!  It's so helpful!
We were investigating an issue with battery voltage stability detection, and it turned out there was no suitable battery graph scaling in the log viewer code!
So I grabbed your PR, and was able to zoom in, using min/max, to whatever values I needed, to properly investigate the problem.
Already a lifesaver!  Thank you!

2024-02-05 10:00 UTC, demvlad commented
> @demvlad - hey I found this PR incredibly useful already! 

There are very nice!

I have one notice to your last PR about debug GYRO....
I get this branch and add the min-max in your code. But i have not found some units convertors for this debug mode in source code. I add their in my code. Please check it.

2024-02-05 12:29 UTC, demvlad commented
> I have one notice to your last PR about debug GYRO.... I get this branch and add the min-max into your code. But i have not found some units convertors for this debug mode in source code. Other gyro debug modes have it

Or it does not need converter?

2024-02-05 14:44 UTC, demvlad commented
There are some improvements today.
- exclude influence of smoothing at min-max values computing. That was reasone of artifacts in minmax sometime.
- resolved issue: wrong min-max values for new curves (before saving).
- added minmax support for new gyro debug by @ctzsnooze.

I have checked many curves - all work good. What units we see at charts, same we see at minmax. If you will find some units issues, please inform me.
I am going to push the branch after some hours.
I am openning PR for review when will do that.

2024-02-06 14:44 UTC, demvlad commented
I think, there is last update this version.
I've resolved some small issues, what i've found:
- properly compute min max values when add new single or group curve, change of name existing curve.
- restore charts view after change when close dialog box by mouse click out of window.

If there are no notices, then i will move forward: 
- will remove MinMax enabled checkbox.
- will add min-max values from presets as default
- will add context menu action to restore presets min-max values

2024-02-06 23:54 UTC, ctzsnooze commented
Please go ahead, looking good!
Let's switch entirely to min/max and remove the old method.

I only notice one issue at present; with a debug trace, if go to 'Graph setup', enable min/max, over-ride the suggested values (eg is suggested is 450-1467, and I change to 0-2000), then click 'save', when I come back later and open `Graph setup` again, my changes to the 'Min' values are lost.

2024-02-07 02:35 UTC, demvlad commented
> ... if go to 'Graph setup', enable min/max, over-ride the suggested values (eg is suggested is 450-1467, and I change to 0-2000), then click 'save', when I come back later and open `Graph setup` again, my changes to the 'Min' values are lost.

Thank's. 
I'm checking this.

2024-02-07 05:44 UTC, demvlad commented
@ctzsnooze 
I'm sorry, but i can't repeat this issue. All are work in my case. Please, send to me the log file and full description yours actions.

2024-02-07 14:05 UTC, nerdCopter commented
> @ctzsnooze I'm sorry, but i can't repeat this issue. All are work in my case. Please, send to me the log file and full description yours actions.

@ctzsnooze , may need to reload your workspace (i saw weirdness one time after testing older commits of this PR).  also recommend sending @demvlad your workspace for completeness sake.

2024-02-07 14:35 UTC, demvlad commented
Hello!
I've pushed final version and wait your notices.
@ctzsnooze Yes, Debugs have too much parameters. I've set min-max for their, follow the curves description in graph_config.js and units converters in flightlog_fields_presenter.js. Please check it and inform me if i take any errors.

2024-02-07 20:46 UTC, haslinghuis submitted a review, later dismissed

2024-02-07 20:55 UTC, haslinghuis commented
Checked out PR - tried with 3 different logs - and get

![image](https://github.com/betaflight/blackbox-log-viewer/assets/8344830/9bbdfb3e-6169-40df-a5ce-9e4b6a4faf9d)

One BBL also fired

![image](https://github.com/betaflight/blackbox-log-viewer/assets/8344830/1212a0d8-ec97-407b-a902-e1ae82ad3584)

2024-02-08 02:01 UTC, demvlad commented
Will check. Can you send to me this logs?

2024-02-08 05:03 UTC, demvlad commented
@haslinghuis 
Ok, i see these errors.
To see it, i've openned the standard BBE release, openned and saved charts configuration, exitted from prigramm. Then i've got these errors when i run new version.
I think, that is error that @nerdCopter  written about.
I will resolve this.
Temporary solution this problem: 
- run standard version, open charts cfg dialog, remove all charts and save. The new version will run good after this.
- or run new programm, open charts cfg, save and exit.
- or full remove prev configuration manually.

2024-02-08 05:08 UTC, demvlad commented
> Will check. Can you send to me these logs? What can i do to see errors? Can i run debuger?

@haslinghuis 
I need only your BBL file with second error to check it.

2024-02-08 14:18 UTC, demvlad commented
The branch was updated.
There are no problem when program is ran firstly with installed before standard BBE version.

2024-02-08 17:05 UTC, haslinghuis submitted a review, later dismissed
Seems to work as expected.

2024-02-09 16:02 UTC, mituritsyn commented
have this error on second workspace:

`Uncaught TypeError: Cannot read properties of undefined (reading 'min')
    at FlightLogGrapher.refreshGraphConfig (grapher.js:915:118)
    at notifyListeners (graph_config.js:11:25)
    at GraphConfig.setGraphs (graph_config.js:36:9)
    at GraphConfig.adaptGraphs (graph_config.js:130:14)
    at newGraphConfig (main.js:1004:27)
    at zoomGraphConfig (main.js:1405:17)
    at HTMLHeadingElement.<anonymous> (graph_legend.js:102:24)
    at HTMLHeadingElement.dispatch (jquery-1.11.3.min.js:4:8549)
    at r.handle (jquery-1.11.3.min.js:4:5252)`
    
[workspace.json](https://github.com/betaflight/blackbox-log-viewer/files/14223824/workspace.json)

    
[BTFL_BLACKBOX_LOG_20240209_221643_KAKUTEF7MINIV3.txt](https://github.com/betaflight/blackbox-log-viewer/files/14223827/BTFL_BLACKBOX_LOG_20240209_221643_KAKUTEF7MINIV3.txt)

2024-02-09 16:08 UTC, mituritsyn commented
couldn't fight this error either:
`Uncaught TypeError: curve.lookup is not a function
    at plotField (grapher.js:329:31)
    at FlightLogGrapher.render (grapher.js:807:25)
    at animationLoop (main.js:288:15)`
    
    I have opened my workspace as previously recommended, performed a save and still see these errors.

2024-02-09 16:17 UTC, demvlad commented
> couldn't fight this error either:t
> Uncaught TypeError: curve.lookup is not a function


This is starnge.. I thought that i resolved this issue. 
I true understand, that you run the last version of programm?
I will think...

2024-02-09 17:12 UTC, demvlad commented
@mituritsyn 
Yes, I confirm, there is a clipping on your example sometime, when fit curves to current window. Sometime all work good, sometime no. 
But i ran program after standard version twice and do not see the the "Uncaught TypeError". The programm create min-max fields an set it to -500 +500 in first run correctly.
Thank you for information. I will think.

2024-02-09 17:27 UTC, demvlad commented
@mituritsyn 
Yes, I think I've caught "Uncaught TypeError". It appears when i load your .json file. I did not check this variant before. Thank's. I will resolve this issue.

2024-02-09 20:22 UTC, demvlad commented
Updated.
added prevention of errors when olde workspace is loaded. The min-max values are set to default in this case.
To do correct saving of workspace with inputed min-max values need a little more time...

2024-02-10 05:45 UTC, demvlad commented
> .... The min-max values are set to default in this case. To do correct saving of workspace with inputed min-max values need a little more time...

What i think about?
Will this helpfull, to save temporary min-max values to workspace file? It will be in one case only: if you want to save some correction of default presets values to workspace. In orher cases you will not use previous temporary min-max values in future.
And second linked question:
I am saving temporary charts min-max configuration always today. But, is it helpfull for other programs run, other logs or other track in BBL logs firmat?
May will better to set minmax from presets default in those cases?
What are yours opinion?

2024-02-10 11:05 UTC, demvlad commented
> ... To do correct saving of workspace with inputed min-max values need a little more time...

I've checked, it seems, that workspace data is saved allready in current version. I don't have to do anything for this, all are working.

Please, check the work of workspaces.
I wait your opinion about my question before.

2024-02-10 22:45 UTC, ctzsnooze commented
I checked and the min/max values seem saved in the workspaces.

Code is working really well.  I'll need to look at the coding behind setting min and max default values.

Only one 'fundamental' question.... what do we do with 'zoom'?

If the user changes min and max on a debug trace, for example, zoom still says '100%'.  Changing zoom doesn't appear to work while custom min and max are in place.

In fact at present zoom doesn't appear to work at all?

So we should be removing the 'zoom' value?

Then the next step would be to remove the old graph_config stuff (offset, input range, output range) and associated code, leaving only:

```
                                power: 1.0,
                                MinMax: {
                                    min: 0,
                                    max: 500
                                }
                            };
```

Assuming power is used as the default expo setting?

It will seem strange, for a while, to not have the 'zoom' function, but I think I'll get used to not having it fairly quickly.

Personally: I think we just remove all the old 'zoom', `offset`, `range` code, completely.

2024-02-10 22:49 UTC, ctzsnooze commented
PS in special cases like this, for RC smoothing debug, we match the scale of the RC commands to be close to the gyro values.  We should probably keep doing this if possible with min/max.  

so in `case 'RC_SMOOTHING'` min would be 1000 but default max would be related to `gyroScaleMargin`, not set hard at 2000.

I'm happy to work through these changes with you, or I can make a branch with suggestions in next day or so, and you can then add them to this PR.

2024-02-11 06:53 UTC, demvlad commented
@ctzsnooze , thank you!
Yes, The offset, range are no need now. There are next step of code optimization. 
About zoom. Fit curve works good instead of some manual zoom. I can add the service action in menu to do zoom at inputed procent value for some cases.
I will add gyroScaleMargin to max value for RC_SMOOTHING.

2024-02-11 20:00 UTC, demvlad commented
I hope, I've resolved issue of wrong min-max computing (The charts clipping by @mituritsyn ). 
Please, check this.

2024-02-12 00:16 UTC, ctzsnooze commented
@demvlad thank you for updating.

I am using your builds for all my log viewing stuff, so I am finding usability things.

You will notice also probably if I draw attention.

RPM values... would be best to perhaps default to 0...40000 say.  At present I get min/max of the values in the log, not very helpful :-(  This I think is because the same issue existed before, it is not your coding, but because it wasn't fixed before.  If these things can be fixed, would be good.

Zoom... we have to address some things.  

At present if I enter a zoom value, it zooms... but then the min and max are showing the same numbers, whereas the trace is very different.  

So if like I have a motor trace 0...100, and click zoom 200, then the min...max scaling is 25...75.  But it still shows as 0...100.  

And for example if I already set min...max to 20...80, and then zoom to 50%, I think that zoom works either side of centre, so the range was 60, or 30 either side, zooming in twice means 15 either side, so the new min...max should be 35...65, in this example.

Hence I think that if we are to utilise the 'zoom' function, then it needs to alter min and max, and we display with min and max.

Another practical thing I am noticing, but it is quite a big ask, because it is a new feature...

Let's say I want to look at range 20-80% of motors traces...
There are 4 motor traces.  I have to edit each one individually, takes time.

Would it be possible to have a method where we can somehow enter apply the min/max to 'all' traces?  This would only be relevant where all traces are basically scaled the same, but that is quite a lot, eg motors, PIDs, gyros, setpoints, etc. And some (but not many) debugs.

I was thinking that it could be nice if there was a tiny 'apply to all' button on the right side, like the trash icon, which applied the settings from that line to all the others in the graph.  

This would also simplify changing the line thickness, expo and smoothing and so on.

Its a new feature so don't worry about it explicitly at this point, just something I thought of that would be super useful.

2024-02-12 01:35 UTC, ctzsnooze commented
@demvlad 
Testing current version, and there is an issue if the previously reviewed log had say a max rate of 400 deg, I view that, and get min...max to range -400...400 on each channel for setpoint, gyro, rc_command, all the channels that should default to the max rate range.
I then close the log, open an other.
This user has max rates -600...600.
But my settings are all -400...400 and must be changed manually.

Hence it is needed that these min...max values must be set to the max rates value on opening any new file.

Thanks.

2024-02-12 03:27 UTC, demvlad commented
> Hence it is needed that these min...max values must be set to the max rates value on opening any new file.

@ctzsnooze 
I agree, the previous settings aren't helpfull for new log or new track in BBL file. And i think, there aren't helpfull to save their in workspace too.
I suggest to set min-max to default presets value in next cases:
- open new log file
- change track in current BBL file
- load workspace

2024-02-12 04:24 UTC, demvlad commented
> Let's say I want to look at range 20-80% of motors traces... There are 4 motor traces. I have to edit each one individually, takes time.
 I was thinking that it could be nice if there was a tiny 'apply to all' button on the right side, like the trash icon, which applied the settings from that line to all the others in the graph.

@ctzsnooze 
I suggest to add the service actions in context menu with labels: 
- apply min-max from this curve to all
- apply min-max from this curve to selected*

*i will try to do menu with checkboxes to curves selection
Please, correct my menu labels caption, if it is need.

2024-02-12 04:28 UTC, demvlad commented
@ctzsnooze 
About zoom. Yes, olde zoom and new minmax are unlinked and have unlogical behavior..

2024-02-12 05:01 UTC, demvlad commented
> RPM values... would be best to perhaps default to 0...40000 say. At present I get min/max of the values in the log, not very helpful :-( This I think is because the same issue existed before, it is not your coding, but because it wasn't fixed before. If these things can be fixed, would be good.

@ctzsnooze 
How work these charts in current version, when i've

2024-02-12 05:17 UTC, mituritsyn commented
@ctzsnooze how do you get updates on this branch? I've checked out with

```
git fetch origin pull/689/head:test689
git switch test689

```
usually I could just use git pull, but on this branch i have this error:

```
$ git pull
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> test689
```

2024-02-12 15:15 UTC, demvlad commented
Updated.
Added service context menu actions:
- 'Fit all curves to zero offset at global full range'
- 'Fit all curves to zero offset at window full range'
- 'Apply this curves min-max to all curves'
- 'Apply this curves min-max to ...'

2024-02-13 14:31 UTC, haslinghuis commented on js/graph_config_dialog.js
> +=======
please remove leftover from merge conflict

2024-02-13 14:31 UTC, haslinghuis commented on js/graph_config_dialog.js
> +>>>>>>> origin/min_max_chart_settings
please remove leftover from merge conflict

2024-02-13 14:41 UTC, demvlad commented
Updated.
Please pay attention on menu action "Apply this curves min-max to ...".
This is the new feature - menu with checkboxes to group action. You can checked several curves at one time, then click menu item "Set min-max ..." at bottom menu. The action will apply to all selected curves.
If it will work good, then i will use this feature to other group action (set one scale for selected curves and other...). 

Also i,ve made some menu optimization. If there is one curve at the chart only, then only single menu actions are showed in context menu.

2024-02-13 14:43 UTC, demvlad commented on js/graph_config_dialog.js
> +>>>>>>> origin/min_max_chart_settings
One time ...

2024-02-13 14:59 UTC, demvlad commented on js/graph_config_dialog.js
> +>>>>>>> origin/min_max_chart_settings
Updated

2024-02-13 15:52 UTC, haslinghuis commented on js/graph_config.js
> +//!!!!!! The stats data have small issues of min-max data !!!!
Usually we mark these with a TODO
```suggestion
TODO - The stats data have small issues of min-max data !!!! 
```

2024-02-13 15:52 UTC, haslinghuis commented on js/graph_config.js
> +//!!! Use new function while stat data issue do not resolved
```suggestion
    TODO Use new function while stat data issue do not resolved
```

2024-02-13 15:55 UTC, haslinghuis commented on js/graph_config.js
> +            for(var i in arguments) {
```suggestion
            for (const i in arguments) {
```

2024-02-13 22:47 UTC, ctzsnooze commented
Wow!  the drop-down contextual menu on min-max is very powerful indeed.

Perhaps it is a bit complicated as well...  :-)  perhaps there is a challenge to focus it to user needs and keep it simple.

What is intended with `fit all curves to window full range`?  It seemed to zoom in so far that the data wasn't usable.  After saving, and coming back to the config dialog, the zoom was lost.

Maybe:

| Name | function |
| ---- | -----|
| All to default | Restores default values to all curves |
| All to this one | Sets all curves to be the same as this one |
| All to ... | Opens dialog to choose which curve to set all to |
| All centered | centres all curves using highest of current min/max |
| All full range | shows full range of all curves, not very useful for comparisons |
| divider |  |
| Set this curve to default | to default |
| Set this curve to : | pop-up to choose a source curve |
| Center this curve | centres it |
| divider | |
| save all curves as default | writes all curve settings in this group to the saved set |
| save default for this curve | writes only this curve to default in the saved set |

Awesome!

2024-02-13 22:50 UTC, ctzsnooze commented
The only thing left is to tidy up the zoom function.

2024-02-14 02:44 UTC, mituritsyn commented
Maybe there is a sense to put or duplicate the context menu on the main screen?

![image](https://github.com/betaflight/blackbox-log-viewer/assets/15355893/fe27b8c6-d266-4db5-ab2a-b15b08c5483c)

2024-02-14 03:04 UTC, demvlad commented
> Maybe there is a sense to put or duplicate the context menu on the main screen?

@mituritsyn , Our thoughts are the same :).
I think about it I want do this in future., when all technology will be ready. This will usefull for fast actions, when does not need the manual min-max settings.

2024-02-14 03:24 UTC, demvlad commented
@ctzsnooze , thank you!
Yes, we do not need to save settings every time. I will make menu action for these.
We have one more way to arrange menu - the submenu hierrarhy. My be place some less usefull menu to submenu.

2024-02-14 03:27 UTC, demvlad commented
> The only thing left is to tidy up the zoom function.

I want to remove zoom and other unused data fields today.

2024-02-14 13:32 UTC, demvlad commented
> What is intended with fit all curves to window full range? It seemed to zoom in so far that the data wasn't usable. After saving, and coming back to the config dialog, the zoom was lost.

@ctzsnooze This action computes local (what we see at the window) min-max values for all curves and apply it. Yes, if some curves has small change at winfow time interval, small noise for example, then it will fit to full charts range! It is looked not well... May be better, to use this action for single curve only, when it is really need.
Small notice about these: i can not catch bug what you writen about, when min-max data are not saved after this action.
About arranging of menu.
Tottaly, we have next actions classification:
- by time range: global (full log data) or local (window data);
- by curvres presentation: in full range or with zero offset;
- by curves count, that we change at one menu action: single curve, all curves, several curves.
There are 2*2*3=12 variants as minimum!
What we have for these:
- menu items with separators and checkboxes;
- ierrarhucal submenu.
How make good menu arrange? Will think.

2024-02-14 14:35 UTC, demvlad commented
Updated:
- completely removed zoom, offset, inputRange, outputRange from curves definition
- added menu action 'Fit curves to same scale ...' - you can select several curves at one time to fit their to same scale. The curve what was clicked to show context menu is checked by default. Please, check this menu action.

2024-02-14 15:35 UTC, demvlad commented
> Save all curves to defaults	writes all curve settings in this group to the saved set
> Save default for this curve	writes only this curve to default in the saved set

@ctzsnooze 
I think, maybe add the small checkboxes with caption 'save' into curves row of table in Charts setup dialog box to indicate, what curves minmax we want to save? Set it checked (or maybe unchecked) as default and change their if it is need.
And follow question, what will do with unsaved curves in next time: to use default presets values or previous saved values?

2024-02-15 01:01 UTC, ctzsnooze commented
Thanks again for actively pushing this forward.

I tested the latest build - really nice to see 'Zoom' gone!  Much tidier in graph_config.js now.

The question of 'defaults' and 'saving' is complex.

In the past, any changes you made to the last used screen setup were 'remembered' when you re-opened.  Changes that were not saved were still present; you came back to a config that was exactly how you left off.

'Saving' meant writing values with `shift<number>` to one of the 10 configuration slots.  Unless explicitly saved, changes were lost.  

'Defaults' were a third concept.  If a graph region was enabled, it always got the default configuration from BBE.  So I think that a 'revert to defaults' should mean, 'revert to the default min/max values in BBE, as if you were opening this graph from scratch'.

On the other hand, a 'revert to saved' would have a different meaning.  If the user had made some changes to those graphs (not the same as default) and had saved those values into the current configuration slot, then a 'revert to saved' would action the values saved in that slot.  If no values had ever been saved, a 'revert to saved' would find nothing saved, and hence would return defaults.

Overall it is looking really good.  Some things I noticed:
- the contextual menu choices seem a bit too complicated, pls see my simplification ideas above
- when a graph is based on max RC rate, eg setpoint, gyro, raw gyro, gyro_scaled debug, RC Command etc, choosing the 'set scale to default' type menu selection should, I think, set the graphs to the max RC Rate.  Currently that doesn't happen.
- What should happen to graphs of the RC Rate type when the user saves the min&max to a config slot?  Currently in the PR it seems that the min and max are locked, and enabled when that config is loaded.  This means that on opening a new log, which may have very different max RC Setpoint Rate, we get the numeric config from the last saved version.  That's a change from previous behaviour, where if the zoom was left at 100%, the max RC Setpoint Rate always set these values whenever a log was loaded.  There was no 'saving' of the min/max for these types of data.  Now I guess we will have to decide what to do here.  Personally I am unsure.  On occasion in the past a user would configure a max rate of say 450 deg/s and of course that is a lot easier to achieve than 900 deg/s.  But the auto-scaling of max-rate-dependent graphs meant that they looked the same.  So... although it's a change from the past, I think that probably we *should* save the max rate into the config slots; that way we get consistent scaling when opened.  The alternative is to always open any such graphs at the RC rate - the old way.  Perhaps there could be a user-selectable option?  For now let's leave it as-is and see how it goes.
- if we remove zoom, perhaps we could have zoom in/zoom out (50% change) in the context menu? 
- to remove ambiguity, the `Save Changes` button in the `Graph Setup` dialog should be re-named `Apply Changes`.  That's because it only applies the changes temporarily.  To save the settings to a config slot, the user must key in shift-n. It would be nice if command-S on mac (control-S on windows?) would save to the current slot.

Looking really good, thanks for all the changes!  Didn't see any bugs!  Awesome programming work!  Thank you!

2024-02-15 05:04 UTC, demvlad commented
> when a graph is based on max RC rate, eg setpoint, gyro, raw gyro, gyro_scaled debug, RC Command etc, choosing the 'set scale to default' type menu selection should, I think, set the graphs to the max RC Rate. Currently that doesn't happen

@ctzsnooze 
I've tryed to use olde default settings for all curves. I will check these curves.
The rcCommands, the Debug GYRO_* use formula maxDegreeSecond(gyroScaleMargin). Can i set margin to 1?

2024-02-15 13:15 UTC, demvlad commented
@ctzsnooze 
One notice.
We can do multiple curves selection with checboxed menu now- to select one, all or several curves.
Maybe use this instead of "..All.." actions (or ".. this" actions)? Or maybe use this allways..
The "All .."and "This..." actions are more quicly (one mouse click). The multiple selection is more universaly, but more slowly (several mouse click).

2024-02-15 13:22 UTC, demvlad commented
> All full range	shows full range of all curves, not very useful for comparisons

@ctzsnooze 
What time interval suggest you for this action - global (all log file) or local (what we see at the charts). Or maybe make the submenu with two items for selecting?

2024-02-15 14:36 UTC, demvlad commented
Updated.
Added Zoom action into menu.

2024-02-15 14:57 UTC, demvlad commented
Please, pay attention at work of menu.

I work in Windows 10 and have a strange bags sometime.
Some time, there is no action after menu item mouse click. The menu is closed without action. I've checked - there is no call of mouse click event handler in this cases. I've checked and not found some mistake in my code. All menu item have handlers, and all handlers are defined at the moment the menu show. But many times all are working and some time is not. But all are work everytime after second time menu opening and item mouse click in this case.
The second bug appears hardly ever : full crash program (it is exited without any messages) after mouse move  under checked menu. The simple mouse moving, without click. I can not understand the reasons of this bugs till. Please, inform me if you catch these bugs.

2024-02-15 15:21 UTC, nerdCopter commented
i don't know "professional" programming/JavaScript, but maybe need `promise` requirement in the code -- again, this is just an uncertain thought.

2024-02-15 15:48 UTC, haslinghuis commented
Need more specific info - which steps are needed to reproduce?

2024-02-15 16:02 UTC, demvlad commented
>  `promise` requirement in the code..

....  asynchronous operation?
The simple example of code from nw.js documentation work good. I want to make simple program with simmilar menu structure and check it.

2024-02-15 16:17 UTC, demvlad commented
> Need more specific info - which steps are needed to reproduce?

The first bug: open the context menu and select any curves action for single "..this curve" or all "..all.."curves. Sometime it does not work, the menu is closed without result.
The second bug: open context menu and select item with multiple action with checked menu. For example - the new Zoom menu. Move mouse under menu, move out menu and back in.. Do mouse click on checked menu item.  Some time the programm is crashed... 
The bugs appears randomly..

2024-02-15 16:26 UTC, demvlad commented
I've tried to remove all content of mouse click handlers and put alert call only. But the first bug appears some time...

2024-02-15 16:57 UTC, demvlad commented
The multy-checked menu has small hack- i create new context menu every time after previous menu is clicked by mouse, to collect all checked action at one time. But i do not think that is a unacceptable operation. And bug can appears on first checkboxed menu, before any mouse click.

2024-02-15 18:19 UTC, demvlad commented
> On one occasion had the issue when moving mouse down the screen after opening context menu the app closed it self.

Yes, this is the second bug. But i saw it on checkboxed menues.
There is some common menu issue... this appears not only on checboxed menu...
The simple mouse move, no any menu action..

2024-02-15 18:21 UTC, demvlad commented
> After choosing zoom - have to select again for the fields we want to apply to ? If so maybe add a header in the menu like `Apply zoom level `

Yes, this is possible.

2024-02-15 19:23 UTC, demvlad commented
> On one occasion had the issue when moving mouse down the screen after opening context menu the app closed it self.

... the program stay in memory after bug in Windows. I kill the task manually by task manager.

2024-02-15 19:26 UTC, haslinghuis commented
Any suspended tasks in task manager?

2024-02-15 19:32 UTC, demvlad commented
I've seen the 3 BBE process in task manager after a bug.
Yarn start does not work, while these process are existed...

2024-02-15 19:49 UTC, demvlad commented
> The context menu does not show in full when at the bottom of the

The reasone for this: you have one curves only. I do not show group action items in menu in this case.

2024-02-16 12:04 UTC, demvlad commented
@ctzsnooze Thank's
I think, all tools are ready today.
Let's optimize the menu contents now.
I do not quite understand, what is mean this action:
All to ...	Opens dialog to choose which curve to set all to.
I will update the branch soon.

2024-02-16 13:24 UTC, demvlad commented
> I personally think that we just want to change one trace, then apply the selected trace to all. That's the most common way of working.

@ctzsnooze 
Yes this is good.
I thought about: full-range, center if it is need, set to one scale. This maybe apply for good parameters (is not small noise). There is some "auto" mode, without manual values input.

2024-02-16 15:05 UTC, demvlad commented
Updated.
There is the new menu items order.
@ctzsnooze I've tried to realize yours variant. With small improvization. I try to use multiple curves selection instead of "All.." action in some places. The "All to ..." action is disabled till (I wrote about it in previous message). I've move olde unused menu items to separate submenu till. I am waiting yours next suggestions.

2024-02-16 15:25 UTC, demvlad commented
@haslinghuis 
I've written to NW.js Discord chat about bugs.
They suggest make the simple program with simmilar menu and check it. I am going to do that in next time.
I asked about some bug diagnostic (log file or any same). There is an answer:
Npm creates a log file when it fails to run. I think there are some chromium crash logs that can be surfaced. But most likely you'll want to use something like nwdc.
Can you help, how to use these tools?

2024-02-16 16:19 UTC, haslinghuis commented
Follow step 2 in https://github.com/nwutils/nwdc?tab=readme-ov-file#usage-for-development-environment-with-nodejs-installed.
```
Add nwdc to the NW.js application being developed:

yarn add nwdc


Run the NW.js application using npx nwdc . instead of nw ..

Press CTRL+C or close your NW.js application normally, to stop the nwdc.exe process.

```

Might be able to use `nwdc.exe` from https://github.com/nwutils/nwdc/releases instead of using `yarn add nwdc`

2024-02-16 16:27 UTC, demvlad commented
> but again, applying zoom to one, then choosing again to apply that trace to all of them is OK

@ctzsnooze 
The zoom is simpy today. The min-max values are multipled to given zoom value every time. That is all. The program does not remember what tottaly zoom value was applied. Therefore is not posible apply same zoom to other curves. We can only:
- aply zoomed curves min-max to other curves
- or place zoomed curve in same scale with others.
I think, it is posible do remembed zoom in future, if this will need.

2024-02-16 16:30 UTC, demvlad commented
> Follow step 2 in

@haslinghuis 
Ok. Thank's

2024-02-16 19:02 UTC, demvlad commented
I take the index.html context menu example from NW documentation and place my menu code into it. The bodies of functions contain alert call only.  I've tested it about 15min. I've catch the bug when the program was close self one time and bug when there is no menu item click handler call some time.  NW discord advices to make the much small code and write issue to github.

2024-02-17 16:52 UTC, demvlad commented
What i've knew about bugs from discord..
I am not one..
https://github.com/nwjs/nw.js/issues/7996
https://github.com/nwjs/nw.js/issues/7909
https://github.com/nwjs/nw.js/issues/7719

I am writing the issue report to NW github.
But, these bugs are since 2021!...
Will think anythingelse instead of this menu

2024-02-17 19:30 UTC, demvlad commented
To be honest, I'm surprised, how that all work on github. Seems i can not do anythig, but link on my pull request is appeared at olde issues on NW pages. I've added comments only to their.

2024-02-19 07:24 UTC, demvlad commented
I think to continue work at this version to do good users interaction. Maybe NW will resolved the context menu issues in future.
But in parallel i will make the second version. I try to make menu by using HTML, JS, CSS only.

2024-02-24 04:13 UTC, mituritsyn commented
this PR keeps clipping my logs on top of it zoom by shift+scroll doesn't work anymore

![image](https://github.com/betaflight/blackbox-log-viewer/assets/15355893/a31a86bb-734f-4b1f-95e7-3148f11e6275)

2024-02-24 05:16 UTC, demvlad commented
> this PR keeps clipping my logs on top

Please, send log file

2024-02-24 07:12 UTC, mituritsyn commented
> > this PR keeps clipping my logs on top
> 
> The olde zoom is not work now. Please send the logfile. What did you do to get this result

i'm just open logs with my workspace. 

![image](https://github.com/betaflight/blackbox-log-viewer/assets/15355893/135c04fd-69d9-40b4-8c08-e39b74c411f7)
![image](https://github.com/betaflight/blackbox-log-viewer/assets/15355893/6562b78a-27dd-4204-b042-d87a21754159)

If I add the same chart it's fine so problem somewhere in preexisted workspace handling. 

![image](https://github.com/betaflight/blackbox-log-viewer/assets/15355893/41f01544-6e2c-4faa-aff7-85ca42623e05)


[LOG00025.txt](https://github.com/betaflight/blackbox-log-viewer/files/14392037/LOG00025.txt)
[workspaces (1).json](https://github.com/betaflight/blackbox-log-viewer/files/14392038/workspaces.1.json)

2024-02-24 07:16 UTC, mituritsyn commented
> The olde zoom is not work now. 

This is sad, as it used to be possible to change the scale by simply scrolling. Now one have to go to the graph settings, manually enter the min/max values, save, make sure that scale doesn't fit, and repeat the process few times. Or there is other way?

2024-02-24 08:02 UTC, demvlad commented
> This is sad.... Or there is other way?

There are now other ways till.
There is the zoom option in menu today. The users interface will be improve in the new PR.
But it is possible to restore fast zoom by press hot keys in new code architecture.

2024-02-25 19:18 UTC, demvlad commented
> > The olde zoom is not work now.

There is some faster zoom settings from menu in the new version. But i want to restore olde zoom without menu in any case.

2024-02-27 14:42 UTC, demvlad commented
Due to an bug in the NW.js context menu system, the menu has been completely redesigned.
Now the menu is based on html, css, js. This gives us significantly more design and control options.
The main menu and submenues are not self closed now. You can make many actions in menu and press "Exit" or "Back" items to return.
![MainMenu](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/52d38891-232f-411c-bdd5-fe2fbc410f4c)


We have some simple submenu:
![SimpleSubMenu](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/79102850-1387-4c1a-b2de-d3881b14cfe6)


There is the submenu with checkboxes to select curves.
 If you want to select all curves without submenu, then select these items in main menu while the 'Shift' key is pressed
![CurvesSubMenu](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/21f2dc24-acfc-438b-888d-c47bc26ed73d)


There is the Zoom submenu. You can set zoom procent, and apply it to selected curves many time to get reqiired result:
![ZoomMenu](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/4fe5494e-e02b-4397-b477-d13560916ac3)


The Save menu is not work till. I will think how to make store settings for selected curves.

2024-03-07 15:11 UTC, demvlad commented
The zoom work by mouse scrolling is restored for new MinMax data.
The program code of MinMax control menu is replaced to separately file.

2024-03-08 20:33 UTC, demvlad commented
Seems, i've done what i wanted in general.
Now it is necessary to optimize the menu system and test.

2024-03-08 20:56 UTC, demvlad commented
> * sometimes `SET ....` exits sub-menu, sometimes not. (`selected centered>` requires to click `<back`).

There are normal for some menu item. If it is unpossible to do something after applying menu action, then i close the submenu without "Back".  Maybe it is need to change "Set..." item caption to "Set... and return".

The Esc key to exit will do next time.

2024-03-11 13:35 UTC, nerdCopter commented
@chmelevskij , please see this PR. will custom menus break with Vite WebApp?

2024-03-11 14:31 UTC, demvlad commented
- Esc key works for menu return now
- Improved menu action  'Selected to this one'. It is posible to change MinMax values from menu:

![InputMinMax](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/80982413-e3cd-494c-8630-d811a574f95d)

2024-03-12 14:45 UTC, demvlad commented
The menu is optimized, all auto full range menu actions are placed into separate submenu
![2](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/f1b0615f-8357-4d21-9f28-2d35de09c7f4)

2024-03-12 17:31 UTC, demvlad commented
Added menu 'This curve full range' with submenu
![3](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/4d5ac97b-6cc4-4723-809d-388f802fd633)

2024-03-13 14:10 UTC, demvlad commented
Seems all are ready!

2024-03-13 14:18 UTC, demvlad commented
**The short users manual.**
The curves Minimum and Maximum control tools instead of % scale in the 'Graph setup' dialog box (issue #477).
The current MinMax curves settings are showed at 'Configure graphs' dialog box in the "Minimum" and "Maximum" columns.
![1](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/f4a6cee9-b09a-4234-977f-0ac2825a21b2)
The following MinMax values controls are possible:
- The direct input into table cells at 'Configure graphs' dialog box. It is possible to changes values or set default values by double mouse click at values field.
- By using context menu
To show context menu you must do right mouse click on Minimum or Maximum values field what you want to edit.
The main context menu:
![2](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/57208b8d-2a4f-4493-be37-ad34fd7055cf)
The main menu include following parts:
- The menu actions to edit curves group
- The menu actions to edit one curves what you selected by right mouse click
- The curves zoom
- The save curves MinMax to use in the next time 


1. **The group curves actions:**
- 'All to default' - set all curves MinMax values to default
- 'Selected to this one' - apply MinMax of curves what you selected by right mouse click to other curves. 
  You can change MinMax values and select curves what you need to change by using sub menu items. Click the 'SET MIN-MAX VALUES' submenu item to apply change or click "Back" to return.
  If you want to apply MinMax values to all curves without submenu, then press Shift key while do mouse click at 'Selected to this one' menu item.
![3](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/c262b570-de58-4efd-b5de-25b6e6bc3011)
- 'Selected to one scale' - set selected curves to one scale by using the most big minimum and maximum to all curves.
    If you want to set all curves to one scale without submenu, then press Shift key while do mouse click at 'Selected to one scale' menu item.
![4](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/d620aee6-5e9d-46e6-9698-114346a95ae8)

- 'Selected centered' - set selected curves offset to zero.
    If you want to set all curves to zero offset without submenu, then press Shift key while do mouse click at 'Selected centered' menu item.
![5](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/28dc3f9f-4251-49d9-ae39-0609db9e474e)

- 'All full range' - show submenu to set real minimum and maximum curves values from log data.
    You can set minimum and maximum values from all global log data time or from time inteval what you see at window. 
    It is possible to set the real full curves range or set centered range with zero offset.
![6](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/9928c6d4-5159-48ef-be5c-7af0b4e77b10)

2. **The actions to single curve what you selected by right mouse click, it names is showed in at main menu:**
- 'This curve to default' - set this curve MinMax to default
- 'This curves centered' - set this curve offset to zero
- 'This curve full range' - show submenu to set real minimum and maximum curve values from log data.
    You can set minimum and maximum values from all global log data time or from time inteval what you see at window. 
    It is possible to set the real full curves range or set centered range with zero ofset.
![7](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/b521b451-a63f-4ab2-bb9c-29332b464f08)

3. **'Curves zoom' - The curves Zoom control. You can set zoom procent and apply it many times for selected curves by press "ZOOM IN" or "ZOOM OUT" menu items.**
notice: you can change the zoom by using the mouse scroll while Shift key is pressed in the curves legend at main programm window.
![8](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/49f79a25-cf50-4132-b2cc-432b16b4a579)

4. **'Save' - prepare curves MinMax to save if you want to use it in future for other opening logs or save their minmax values in workspace.** 
    Notices: This action does not save workspace directly. You need to save workspace after this action.
    If you want to use workspace with default curves MinMax values, then reset checkboxes for their (option by default). 
    If you want to save custom MinMax curves values in workspace, then check checkboxes for curves, what needs this.
![9](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/899d69d1-b724-4414-9ea2-b9dbd9a89a5e)
You can prepare curves for save without context menu - by using 'Save' checkboxes in 'Configure graphs' dialog panel
![10](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/173962c1-8454-4bc3-9ee2-8ee9168f509f)

2024-03-13 20:04 UTC, demvlad commented
> @chmelevskij , please see this PR. will custom menus break with Vite WebApp?

@nerdCopter 
I am trying to check my menu in this WebApp. It remains to fix a little bit merge conflicts...

2024-03-13 20:10 UTC, nerdCopter commented
- yes, i merged the two in a local test and gave up rather quickly due to conflicts that i did not wish to resolve.
- i do not know the timeline in which we go 100% PWA, therefore i'm unsure at which time to resolve.

2024-03-14 06:05 UTC, demvlad commented
> * yes, i merged the two in a local test and gave up rather quickly due to conflicts that i did not wish to resolve.

@nerdCopter 
I've resolved merge issues.
Seems, all are working. But it is need to test the both versions.

2024-03-14 12:52 UTC, nerdCopter commented
requesting @ctzsnooze to test the scientific stuff.

2024-03-14 15:45 UTC, demvlad commented
@nerdCopter 
This is the link to merged version vite-web + minmax_menu for testing
https://github.com/demvlad/blackbox-log-viewer/tree/vite-web-minmax-menu

2024-03-14 23:12 UTC, ctzsnooze commented
Hi!  Thanks for so much work, apologies for not responding earlier.

I am now using it and found that, by default, going 'shift-7' to save into setup for the '7' key did not work.  Only when I selected the 'Save' checkbox would it be saved on closing the Graph setup window.

I notice that using '7' or 'shift-7' had the same effect.

Maybe we can use 'shift-7'. like before, to store the entire setup once it is finally correct, regardless of the 'save' checkbox state?  Otherwise the user must check 'save' for each channel.  They can still use the 'save' checkbox if, while in the dialog, they want to save that specific channel, perhaps.

2024-03-15 03:23 UTC, demvlad commented
> I notice that using '7' or 'shift-7' had the same effect

@ctzsnooze Hello!
Thank you!
I did not know, that the '7' key had the magic property. I am resolving it.

2024-03-15 06:37 UTC, demvlad commented
> I am now using it and found that, by default, going 'shift-7' to save into setup for the '7' key did not work. Only when I selected the 'Save' checkbox would it be saved on closing
@ctzsnooze 
I true understand, that you can not save any settings in '7' slot only without checking Save checkboxes? And other slots are working properly.
This is very strange. The all slots have one logic. The Save checkboxes have effect on using minmax values only. It can not has effect on other data store.
 I can not repeate this issue.
Please, could you send yours workspace file and full describe what can i do to see this issue.

2024-03-15 13:13 UTC, nerdCopter commented
@demvlad , for all keys `1`,`2`,`3` ...`0`, pressing the `#` activates custom graphs, `shift-#` saves active custom graphs.

2024-03-15 13:44 UTC, demvlad commented
> @demvlad , for all keys `1`,`2`,`3` ...`0`, pressing the `#` activates custom graphs, `shift-#` saves active custom graphs. 

Yes, i know about this.
I've checked, the '7', Shift+'7' work properly.

2024-03-19 20:09 UTC, demvlad commented
> This is the link to merged version vite-web + minmax_menu for testing https://github.com/demvlad/blackbox-log-viewer/tree/vite-web-minmax-menu

Updated for current vite-web version.

2024-03-20 14:21 UTC, demvlad commented
Improvement:
added menu item action 'centered one scale' into 'All full range'submenu.
Set all curves to one scale by maximal curves values. The setpoint and gyro for example. 
![10](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/9ec0b4b9-471e-47dd-be84-36b011e0ff93)

2024-03-25 14:56 UTC, demvlad commented
Menu view style improvement: remove wrap of text in menu items.

2024-03-25 14:59 UTC, demvlad commented
The vite-web version with MinMax control menu is updated:
https://github.com/demvlad/blackbox-log-viewer/tree/vite-web-minmax-menu

2024-03-27 13:27 UTC, demvlad commented
@haslinghuis 
Please, can you advice, what is better to use for this PR: merge or rebase with master branch?

2024-03-27 13:30 UTC, nerdCopter commented
thank you for all your hard work. 
regarding the new PWA merge to master, please make your PWA version as a a new PR, so that i might play with old PR as standalone app. TYVM.

2024-03-27 13:34 UTC, demvlad commented
> thank you for all your hard work. regarding the new PWA merge to master, please make your PWA version as a a new PR, so that i might play with old PR as standalone app. TYVM.

Ok. This is a good solution.

2024-03-28 23:12 UTC, ctzsnooze commented
@demvlad - I'm using this PR every day, and it is simply fantastic.  I can now make screen displays that scale exactly how I would like them to be scaled.  Much better than before!

I do have some suggestions to make, mostly relating to the user interface.

- Previously going `SHIFT-1` would save the current configuration of the screen to the 'shortcut' setup that can be later 'loaded' by pressing the `1` key.  This doesn't work anymore.  For example, I have an existing screen layout, change the scaling of one line, hit `SHIFT-1`, and that scaling is reverted, as if I pressed `1` without the `SHIFT` modifier.  Probably this should not be broken.

- The dialog which opens, when editing curves, is now very complicated, especially with the secondary pop-ups.  The intent of the dialog is to make it easy and quick to make changes to min and max, to more quickly set the 'save' checkboxes, and to do some tasks like restoring defaults or centering traces.  The utility of the dialog can be measured by whether or not it makes things easier.  Because of its complexity, I often now bypass the dialog for most simple changes, and make the changes to scale with copy and paste, or by manually clicking the 'Save' checkboxes.  That's because the mental effort of locating and choosing the correct options, from a lot of options, is non-trivial.

- My usage is probably similar to most people. For 'normal' (non-debug) traces, eg PID or Motors, I nearly always modify the min and max in the topmost trace, then want to quickly set all traces in the group to those same values. 

- I may want to reset them all to default, or to centre, or set to full range, or zoom all the traces, but haven't needed to use those functions yet.

- Save and Exit are 'unclear'.  In fact `Exit` 'saves' whatever changes have been made.  Exit 'Applies' the settings.  Save doesn't save them, it opens a new dialog.  Historically, the reason the 'OK' button says `Apply Changes` is because these changes were NOT saved to one of the 10 numeric keys, they were just 'Applied' to the current screen view.  If you shifted to some other screen view, those changes were LOST.  You had to go, `shift-N` in order to 'save' the changes you 'applied'.

So what I am wondering about is if you could make it so that the things we use most commonly require only one click, and to rethink the 'save' behaviour.

For example, when the dialog opens, I would prefer something like this.
```
All Curves:
- Like this one 
- Zoom In
- Zoom Out
- Full Range
- Default

This Curve >

[Apply]
```

If you just select any one of the 'All Curves' options, and they are immediately actioned, with no need for any other clicking.

The [Apply] button should be styled to look like an 'OK' button, so the user knows that it is not a menu option, but is something they press.  'enter' or 'return' should perhaps perform Apply.

If the old method where 'shift-N' saves the current setup (all traces on the screen with all settings), then it's not all that common to need the 'save' checkboxes.  If the user is happy with how it is configured, which they only really see after closing the dialog, they can go `shift-N` to save it.  

I would personally like to see the more standard cmd-S save the current screen to the current position.  There are many times where I went 'shift-N' and put the wrong number in, saving a carefully configured screen over the top of the wrong one.  If I had cmd-S to save the current screen, that would be intuitive and safer.  

If we think about the save checkbox....

It forces a save of the changes to those waveforms to be written permanently to the screen setup every time you close the dialog box.  This is both good and bad.  

In the traditional computer environment, if no changes are made to a document, closing it results in no prompt to save.  But if changes are made, when the user tries to exit, they are asked if they want to 'save' the document.  We could do something similar here perhaps; if the user changes a 'screen' setting, then when they hit some other numeric key to choose another screen setup, they get a dialog 'save changes? OK/cancel'.  Otherwise not.

Provided that the old `shift_N` save method is restored, and even better if we had cmd-S to save the screen layout, and were prompted to save on exiting if we changed things, I would not use the save checkboxes at all, I think.  I'd make the changes then decide if I wanted to keep them.

That's the feedback from me, anyhow.  The only 'bug' to fix is that shift-save no longer saves. The rest is just my opinion about how to make it work a bit quicker and easier for common tasks.

2024-03-29 04:40 UTC, demvlad commented
@ctzsnooze 
Thank you very much for review.
I will accept you suggestions about user interface. 
About Save checkboxes. They have one goal:
to change default min-max values for all time if it is need. For example - the new Debug fields, what have not true minmax setting in the source code. While the default behavior  is using of presets min-max, what hardly defined in the source code.

2024-03-29 05:25 UTC, demvlad commented
@ctzsnooze 
About Full range action. I think to set uncentered real curves min-max during all time for most common using.
But we have very big values in the end flight sometime, after hard landing. Therefore i think, will be helpfull do possible to change times interval? I can use standard time range, what we can select by markers.

2024-03-29 06:01 UTC, demvlad commented
> Previously going SHIFT-1 would save the current configuration of the screen to the 'shortcut' setup that can be later 'loaded' by pressing the 1 key. This doesn't work anymore. For example, I have an existing screen layout, change the scaling of one line, hit SHIFT-1, and that scaling is reverted, as if I pressed 1 without the SHIFT modifier.

@ctzsnooze 
I am sorry, but i do not see this issue:
- i set some chart configuration
- press Shift+ num key
and i go to num workspace with new settings.
Then i press other num key and go to other num workspace settings.
Then i press num key with saved workspace and go to it.
The all are working on my PC with Windows 10. 
This is strange, while I did not change the workspace control logic in my source code. 
Please, could you write, what OS do you use?
Sorry, but i can not improve the issue what i can not see.

2024-03-29 06:33 UTC, demvlad commented
@ctzsnooze 
The small notice:
It is possible to run action for all curves without submenu in current version.
If do mouse click by menu items (Selected to this one, Selected to one scale, selected centered) while the Shift key is pressed, then action will apply to all curves without submenu.

But i can easy change the logic: made action to all curves as default by item mouse click and show the submenu when Shift key is pressed.

2024-03-29 14:57 UTC, demvlad commented
Improvements:
The menu is simple now. There are no submenues by default.
If the stanard menu is not enough for you and you want more features, then click menu item while the Shift key is pressed. 
And you will see the submenu with extended actions.
![menu](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/d40c22e6-7d3a-4daf-a0d5-8a7436e6c59e)

The Save item is removed from the menu, because it duplicated the 'Save' checkboxes in Chart setup dialog box.
You need to use the 'Save' checkboxes in one case only: if you want to change default min-max values for some curves by using workspace slots or by loading next logs.
If 'Save' checkbox is not checked for curve then it will use default presets min-max values by loading next logs or workspace charts preset.
I do not like the 'Save' checkboxes name, because the charts configuration will save in any case when you press the Apply button at dialog box or press Shift+num key after that.
I want to find other short name for these checkboxes.

2024-03-29 15:06 UTC, demvlad commented
> i also notice dialog-menus sometimes double,triple, etc and overlap and cannot cancel.

@nerdCopter I've never seen this. 
Please, write me the actions sequence to do this, if it will possible.

2024-03-29 21:14 UTC, nerdCopter commented
it may be some days i'm out of office

2024-03-30 12:15 UTC, demvlad commented
Improved: the right arrow markers are showed at menu items by pressing the Shift key to show the submenu activity.
The default menu:
![1](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/125a330a-dca8-4851-a3d6-cfa6062cd08c)

The menu with active submenu while Shift key is presed:
![2](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/8a3b6936-bc3c-43c2-928e-f10d1aa2f705)

2024-03-30 12:20 UTC, demvlad commented
It seems, there are all till.
All are ready for testing.

2024-03-30 12:42 UTC, demvlad commented
PS: I think, the "Default" tables caption in Chart setup dialog box is better then 'Save'.

2024-03-30 17:19 UTC, demvlad commented
> I would personally like to see the more standard cmd-S save the current screen to the current position.

@ctzsnooze 
I understand you.
I think, there are no problem to make Shift-S key for saving current screen into current workspace slot.
But i think, this will new PR, because this PR is wery thick already.

2024-03-30 17:45 UTC, demvlad commented
>  Therefore it exists the 3 way:
> 
> * allways use default presets minnax as start;
> * allways use last stored min-max as start if curves data were stored, else - use default presets.
> * use selection like checkboxes

It exists other solution:
To use 'Default' checkbox (it had name Save before) for current configuration only. Will it use for next logs or programm starts or no.
The Shift+numkey can store to workspace slot  the all information allways, because it was uncomfortable to set permisson for minmax in dialog box for that.
Therefore we will have 2 separate stream for storing:
- current charts config, which can stored with minmax or without to use it for other logs and programm starts as Default
- the workspace slots for storing full charts configuration to use it in any time.

2024-03-30 19:05 UTC, demvlad commented
> It exists other solution: To use 'Default' checkbox (it had name Save before) for current configuration only. Will it use current curves minmax for next logs or programm starts or no. The Shift+numkey have to store into workspace slot the all information allways, because it was uncomfortable to set permisson for minmax in dialog box for that. Therefore we will have 2 separate stream for storing:
> 
> * current charts config, which can stored with minmax or without to use it for other logs and programm starts as Default
> * the workspace slots for storing full charts configuration to use it in any time.
> I think to apply this save strategy soon.

The workspace save strategy is changed.

I think, that are all till.
I am inviting all participants for testing.

2024-03-31 07:47 UTC, demvlad commented
> All Curves:
> - Like this one 
> - Zoom In
> - Zoom Out
> - Full Range
> - Default
> **This Curve >**

@ctzsnooze 
I am looking at your suggestion and see one improvement!
To make 'This curve' actions as submenu!
This is a fine solution to get shorter menu, because my current releaze is too long.
I accept this suggestion soon.

2024-03-31 09:40 UTC, demvlad commented
The 'This curves' actions replaced into submenu.
Finaly we have next  variants menu:
### Main menu default
![1](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/93b71067-903c-4def-9ee1-c9065525453a)

### Main menu with active submenu while the Shift key is pressed
![2](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/214a679e-aaed-4276-ab0f-f16ab8f1ca27)

### 'This curves' actions submenu
![3](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/f83f52e7-be07-49fb-a466-2924a19b0e5a)

### Main menu if the chart has one curve only
![4](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/631a9a50-ac6a-4c9b-afa4-e14f92a35153)

2024-03-31 09:52 UTC, demvlad commented
The optimization process is endless :)
But i think there are all till....

2024-04-01 00:34 UTC, ctzsnooze commented
Thank you again for doing so much work here!
I deeply value the usability of BBE now, I could never go back!

I am not looking at the build yet, but instead of 'shift' key, is it possible to use the 'option' type of method, like 'right-click' on mouse, or two-finger click on trackpad or optionKey-click?  Those are the 'standard' Mac options.

2024-04-01 00:43 UTC, ctzsnooze commented
OK It is so much quicker and easier now!  Thank you!

One small detail... If I go `Zoom In`, the changes in the values are made immediately, and I see that happen in the fields.  My instinctive response was to then immediately click 'Apply Changes'.  But nothing happened, because I must click `Return`.  

Is it essential to click `Return`?    Could it be possible that both 'Cancel' and 'Apply Changes' are active all the time?  That would be awesome!

Hey also it's very cool that I can change the labels of the curve groups and see the name update.  The live updating of the curve scaling is very cool also.

2024-04-01 03:20 UTC, demvlad commented
> One small detail... If I go Zoom In, the changes in the values are made immediately, and I see that happen in the fields. My instinctive response was to then immediately click 'Apply Changes'. But nothing happened, because I must click Return.

@ctzsnooze Thank you for review!
The all move to goal, to exclude Chart dialog box from min-max control interface:)

2024-04-01 03:45 UTC, demvlad commented
> but instead of 'shift' key, is it possible to use the 'option' type of method, like 'right-click' on mouse, or two-finger click on trackpad or optionKey-click? Those are the 'standard' Mac options.

I will think about other devices type. But i prefer some optionKey, to preview the right arrows on active menu items.

2024-04-01 06:58 UTC, demvlad commented
@ctzsnooze 
I true understand, that Alt key is same as OptionKey in Mac?
Then i will use Alt instead of Shift key

2024-04-01 14:38 UTC, demvlad commented
**Improvements:**
The Apply and Cancel buttons are enabled while menu is open. You can use it to close the dialog box without pressing of Back and Return menu items.
The Alt (optionKey on Mac) key is used instead of Shift to use hidden submenu.
The 'Full range' item of 'This curve' menu has submenu while Alt key is pressed.
The 'Default' item on main menu has hidden submenu too.
The menu source code structure is improved.

The issue of this version what i know, and their resolving at moment:
- sometime the Esc key is not working - to close menu by click at Back and Return menu item.
- sometime the right arrows are not showed on menu items while Alt key is pressed - continue to use submenu with Alt-key. The submenu are working really.
There issues appear sometime after some mouse or keyboard actions while the menu is openned. There are some keyboard event handlers problem, i will resolve these.

**The 'Full range' submenu on 'This curve' menu while Alt key is pressed.**
![sub3](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/da9413da-4f17-40aa-a132-8621ceaed443)


![sub_single](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/3dc6e4af-eeb5-473c-a68e-6808d1c240a0)

2024-04-01 14:43 UTC, demvlad commented
> Is it essential to click `Return`? Could it be possible that both 'Cancel' and 'Apply Changes' are active all the time? That would be awesome!


@ctzsnooze 
The update is ready.

2024-04-02 10:33 UTC, ctzsnooze commented
@demvlad - looking great now!  Nice to be able to just zoom (or whatever) and Apply.  Thank you!

Not sure if its related to this PR, but I noticed that 8-track debugs with only four defined data channels end up looking like this:

<img width="1068" alt="Screen Shot 2024-04-02 at 9 28 18 pm" src="https://github.com/betaflight/blackbox-log-viewer/assets/11737748/2f808ebc-ca58-4547-b7b9-1afd0b7ff968">

Sometimes when I hack these debugs I use the 'unused' channels for development.  Not all debugs are configured properly.

Anyway in this case I was using debug 4 (5th trace) but could not read the values in the graph headers to the right, because 4-7 were compressed up making the values invisible.

Perhaps only compress them up when there are no values to display, but otherwise even without a name defined, let's show the numbers.  The graph is displayed normally.

2024-04-02 10:42 UTC, ctzsnooze commented
Also there is some weirdness happening (on Mac, anyway) when I click in a number field to edit manually.

If, say, I have typed the value 10, just `10`, no decimal point, and I click on it, a small rectangle opens up with `1000.0` in it.  If I click on the `1000.0`, that value is entered.

This issue doesn't arise if there is a decimal point in the value, e.g. `10.0` is fine.
I usually type whole numbers, except in unusual cases.  So I see this issue quite a lot.  Would be good if, after tabbing out of the field, I got 10.0; alternatively, handle numbers without a decimal point like normal integers?

Everything else is really good.

2024-04-02 11:10 UTC, demvlad commented
@ctzsnooze I did not know, what can be the digits precession, therefore i used one digit after coma format.
Ok. Let's try the integer format.

2024-04-02 11:14 UTC, demvlad commented
> Not sure if its related to this PR, but I noticed that 8-track debugs with only four defined data channels end up looking like this:

@ctzsnooze 
Ok. I will look this. Could you send to me this debug log file.

2024-04-02 18:06 UTC, demvlad commented
Resolved issue of  Esc and Alt keys actions.
@ctzsnooze I do not see the issue what you wrote about on my Windows PC.
I've made integer value in min-max input fields in this release. But i formated digits for fields output and it is strange, that it exists issue by value input. Will see.
About Debug fields what have not full data - please send me log file. I will resolve this issue.
About optionKey. I've found that in Vite Web version the Alt-key activate the browsers menu in Windows. Therefore in this version i am using Alt-key and in Vite Web version i am using Shift-key.

2024-04-04 01:33 UTC, ctzsnooze commented
Thanks again @demvlad - those fixes are really nice!
The integer / decimal point problem is fixed on the Mac with your recent update.
I checked with debugs, works nicely.
Very happy indeed and will mark as approved :-)
The only possible user interface thing might be to put some colour or other way to highlight the `Return` command... it's not obvious to users that it must be actioned before they can escape from this 'window'.  
I don't know if it can be done more like a little window with an 'OK' button, to highlight what it does?

2024-04-04 01:33 UTC, ctzsnooze submitted a review, later dismissed
@haslinghuis wonder if you could test and review please.  Functionally this is super useful!

2024-04-04 03:02 UTC, demvlad commented
@ctzsnooze Thank you for help and PR approving!
I will insert the real button element in the Return menu item, it will easy.

2024-04-04 03:12 UTC, demvlad commented
> still get the strange popup behaviour on Mac, but only sometimes, not easy to predict why. The value in the pop-up is always 10x the value in the cell.

@ctzsnooze This looks as some autofill tools.
But i do not use autofill property for this input fields in my programm source code, therefore this behavior is really strange.
I will experiment...

2024-04-04 04:15 UTC, ctzsnooze commented
It is curious that it happens.  I can make a video if the explanation is no good.
Worse for:
- positive values
- values with no decimal point
- the exact default value.

2024-04-04 04:33 UTC, demvlad commented
@ctzsnooze 
I understand. I will try to disable autocompletion. I hope it will work.

2024-04-04 14:44 UTC, demvlad commented
@ctzsnooze Please, check this update.
1. I've disable input autocompletion
2. The active top level 'Return' or 'Back' menu items have more smart design

2024-04-04 15:32 UTC, nerdCopter commented
The NWjs build is obsolete. Closing this PR. It can be re-opened against new branch `3.7.0_NWjs_maintenance` for those of very few us who want a "final" installable; however, after a few weeks±, non-PWA PR's will not be accepted.

2024-04-04 15:46 UTC, demvlad commented
@nerdCopter 
I understand.
But this is an updated version for testing @ctzsnooze. Can i reopen this PR for short time?

2024-04-04 15:47 UTC, demvlad commented
Or maybe better to put link at this branch in vite veb PR comment?

2024-04-04 17:25 UTC, demvlad commented
> Can i reopen this PR for short time?

Thank's

2024-04-04 22:24 UTC, ctzsnooze commented
@nerdCopter this PR is still in active development, in the NWJS framework.  it will be proposed for the non-NWJS method when it's ready, which will be very soon, I think.

2024-04-04 22:48 UTC, ctzsnooze commented
Still get the same pop-up problem as before.

2024-04-05 03:27 UTC, demvlad commented
@ctzsnooze 
This is very interest!
Ok, send video to me pleaae.
Could you do these tests:
- go into extended

2024-04-05 05:07 UTC, demvlad commented
@ctzsnooze 
Could you check this latest version, please. I've changed autocomplete property for minmax input fields.

2024-04-05 06:07 UTC, demvlad commented
> PS one small thing I noticed is that if I open the Graph Setup window, have a look around, but do nothing at all, the escape key won't close the Graph Setup window. It should close on escape key anyway.

@ctzsnooze 
This is deafaul dialog box behavior, because there are no any focused elements at the dialog box.
I've resolved this issue. The both branches will be updated soon.

2024-04-05 10:46 UTC, ctzsnooze commented
I doubt this issue is due to autocomplete, certainly I've not seen autocomplete do this in Blackbox ever before.

`type = "number" has exactly the same  problem, unfortunately.

2024-04-05 12:56 UTC, nerdCopter commented
> @nerdCopter this PR is still in active development, in the NWJS framework. it will be proposed for the non-NWJS method when it's ready, which will be very soon, I think.

yes, understood.  However since the PWA stuff is already merged to master, i proposed making this code a PR against maintenance-branch https://github.com/betaflight/blackbox-log-viewer/tree/3.7.0_NWjs_maintenance .  
Either way is fine by me, i wont argue.  If it is to be built by other users, then it will need to be merged to `3.7.0_NWjs_maintenance` in the long run.

2024-04-05 14:58 UTC, demvlad commented
@ctzsnooze 
Please, check this version.
I do not see the autocomplete or tooltip on my minmax input.
But i've found some solution to kill autocomplete in google

2024-04-07 21:08 UTC, demvlad commented
@ctzsnooze 
This is other variants for testing:

**input type="text" inputmode="numeric":**
https://github.com/demvlad/blackbox-log-viewer/pull/new/min_max_chart_number_input

**input field without form-control class**
https://github.com/demvlad/blackbox-log-viewer/pull/new/min_max_chart_no_form-control

2024-04-08 16:47 UTC, demvlad commented
@ctzsnooze 
I've reverted the all autocomplete preventions commits. Please check this version.

2024-04-23 15:00 UTC, demvlad commented
Improvements:
- the extended submenu action key is changed from Alt to Shift to be same as VITE WEB version
- the curves expo is set to 100% as default (i did not remove it full till).
- added menu items actions to set min-max for marker selected time interval in extended submenu

2024-04-24 14:42 UTC, demvlad commented
Updated:
- the 'Keep' checkboxes are removed from Charts setup dialog box
- the 'Grid' checkboxes are removed from Charts setup dialog box, the grid visibility is control by On/Off button
- the main menu items actions close the menu

2024-04-26 14:50 UTC, demvlad commented
**THE MANUAL**
The MinMax control PR can control curves scale and placement quickly and full.
The current MinMax curves settings are showed at 'Configure graphs' dialog box in the "Minimum" and "Maximum" columns.
![1](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/a50239e7-772c-40b5-a0bc-db04c6d56dea)

The MinMax values can be changed:
- By direct input into table cells at 'Configure graphs' dialog box. It is possible to changes values manualy or set default values by double mouse click at values field.
- By using context menu

To show context menu you must do right mouse click on Minimum or Maximum values field what you want to edit.
The main context menu:
![2](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/e3fd527f-2d10-44f5-bdfb-4baf24c48cbf)

The main menu include following parts:
1. The menu actions to edit all curves
2. The menu actions to edit one curves what you selected by right mouse click (The 'Gyro pitch' for example at the picture)


The actions for all curves:
- 'Like this one' - apply MinMax of curve what you selected by right mouse click ('Gyro pitch' for example) to all curves.
- 'All to default' - set all curves MinMax values to default
- 'Zoom in', 'Zoom out' - change zoom for all curves
- 'Default' - set the all curves MinMax values to default
- 'Full range' - set the all curves MinMax values from Log file data during the all flight time
- 'One scale' - set all curves to one scale
- 'Centered' - The curves are centered around X-axis

The single curve submenu has same actions: 
![3](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/a2e74865-5eef-4194-bbe9-3dced331697d)

The main menu has extended mode. You need press the 'Shift' key to activate it and select the submenu, what you need. 
![4](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/b3070a56-b571-4524-9cfa-e64dbe623250)

**The 'Like this one' extended submenu.**
You can change MinMax values and select curves what you need by using the checkboxes to apply these values. 
Click 'SET MIN-MAX VALUES' item for apply. 
Click 'Back' menu item to go back to main menu. 
Click 'Apply change' or 'Cancel' button on the main 'Configure graphs' dialog box to close the menu and dialog box immediately
![5](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/8037d5b7-ce20-4ad2-914c-994f67751e2b)

**The 'Zoom in', 'Zoom out' extended submenu.**
You can set the zoom procent value and select curves what you need by using the checkboxes to apply zoom. 
Click 'ZOOM IN', 'ZOOM OUT' items for apply zoom
Click 'Back' menu item to go back to main menu. 
Click 'Apply change' or 'Cancel' button on the main 'Configure graphs' dialog box to close the menu and dialog box immediately
![6](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/0ef5f85b-4896-4eb8-af4d-8585bfe5bcfa)

**The 'Default' extended submenu.**
You can select curves what you need by using the checkboxes to apply default values. 
Click 'SET CURVES TO DEFAULT' item for apply
Click 'Back' menu item to go back to main menu. 
Click 'Apply change' or 'Cancel' button on the main 'Configure graphs' dialog box to close the menu and dialog box immediately
![7](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/9164772b-fcf4-4a6c-aa1b-bba974459def)

**The 'Full range' extended submenu.**
You can select curves what you need by using the checkboxes to apply values. 
Click 'At all global log time' menu item to set MinMax values from log data during all time.
Click 'At local window time' menu item to set MinMax values from current time interval at the chart window.
Click 'At markere time range' menu item to set MinMax values from markered time interval what you select by using "I", "O" keys. If it is not select then will apply all log time interval.
Click 'Back' menu item to go back to main menu. 
Click 'Apply change' or 'Cancel' button on the main 'Configure graphs' dialog box to close the menu and dialog box immediately
![8](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/9503c4e3-24c2-413d-880e-38922f7ef89f)

**The 'One scale' extended submenu.**
You can select curves what you need by using the checkboxes to set the same scale. 
Click 'SET SET CURVES TO SAME SCALE' item for apply
Click 'Back' menu item to go back to main menu. 
Click 'Apply change' or 'Cancel' button on the main 'Configure graphs' dialog box to close the menu and dialog box immediately
![9](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/02259788-88aa-46df-85f1-3703e4578eb6)

**The 'Centered' extended submenu.**
You can select curves what you need by using the checkboxes to centered. 
Click 'SET CURVES TO ZERO OFFSET' item for apply
Click 'Back' menu item to go back to main menu. 
Click 'Apply change' or 'Cancel' button on the main 'Configure graphs' dialog box to close the menu and dialog box immediately
![10](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/2a753e33-d4ac-4031-b207-984659293030)

**The single curve submenu has one 'Full range' extended item:** 
It is like 'Full range' extended submenu, but for one selected curve only.
![11](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/9cb0ac50-ae5c-40d4-bc16-f937807357e4)

If you open context menu for one curves chart, then you see the short menu:
![12](https://github.com/betaflight/blackbox-log-viewer/assets/45164139/4209a674-b6df-4c7c-aa8a-26ebe1b3a988)

2024-05-04 12:27 UTC, demvlad commented
The small improvement:
The mouse click at curves on the legend works like toggle button (make the analyser chart as visible/unvisible)

2024-05-09 01:27 UTC, ctzsnooze approved these changes

2024-05-09 13:04 UTC, nerdCopter commented
PWA version was merged.

This PR set as draft and labeled `Do not merge`.
This PR could be recreated against `3.7.0_NWjs_maintenance` if desired, but old github workflows are no longer active. End-users would have to build locally.

This PR should be closed.

2024-05-09 13:17 UTC, nerdCopter commented
although useful, this file should not have been committed.
./Workspace/workspaces-ctzsnooze.json

2024-05-09 13:18 UTC, demvlad commented
Ok. I am closing this PR, but the github branch will be active sometime.

2024-05-09 13:21 UTC, nerdCopter commented
i briefly tried to recreate a rebase and/or squash, but there were conflicts that i was not keen to fix.  if you feel like doing it, welcome.

2024-05-09 14:44 UTC, demvlad commented
> although useful, this file should not have been committed. ./Workspace/workspaces-ctzsnooze.json

Yes, i will do this workspace as default in this version too.

2024-05-09 17:30 UTC, demvlad commented
Closed!

2024-05-09 17:53 UTC, closed without merging