Actual log rate computing for spectrum computing
betaflight/blackbox-log-viewer pull request #711
Opened 2024-02-28 18:45 UTC by demvlad

My tinywhoops Happymodel F411 flight controller has 1/3 data lost by writing flight data to Highspeed Openlagger serial device with 2k log rate.
The BlackBoxExplorer shows wrong frequency at the spectral
diagramm. The reasone this is the big difference between
actual log rates and Betaflight value what BBE calculates by configuration data.
This PR resolved this issue.
It calculates actual log rate once, and compares it with config values.
If the difference is above 5%, then the FFT algoritm uses the actual rate value. The warning message is showed at the spectr chart in this case.
I've tryed to use actual rate allways without condition and  checked this at my olde good logs from 5" quad. It had about 2002Hz actual rate instead of 2000. But even in this case i've seen not integer value at charts freq axis. Therefore i use actual rates in case of relative big diffetence only.

This code has bad algoritm of compute log file records count. 
@mituritsyn solve this task better.
I suggest to join our code together.

2024-02-28 20:18 UTC, nerdCopter commented on js/graph_spectrum.js
> +        this.plotSpectrum =    function (fieldIndex, curve, fieldName) {
```suggestion
        this.plotSpectrum = function (fieldIndex, curve, fieldName) {
```

2024-02-28 20:19 UTC, nerdCopter commented on js/graph_spectrum.js
> +                const logRateInfo = dataLoad();
```suggestion
                const logRateInfo = dataLoad();
```

2024-02-28 20:19 UTC, nerdCopter commented on js/graph_spectrum_calc.js
> +    if (this._actualeRate == undefined) {
```suggestion
    if (this._actualeRate == undefined) {
```

2024-02-28 20:19 UTC, nerdCopter commented on js/graph_spectrum_calc.js
> +        this._analyserTimeRange.in = this._flightLog.getMinTime();
```suggestion
        this._analyserTimeRange.in = this._flightLog.getMinTime();
```

2024-02-28 20:19 UTC, nerdCopter commented on js/graph_spectrum_calc.js
> +        this._analyserTimeRange.in = minTime;
```suggestion
        this._analyserTimeRange.in = minTime;
```

2024-02-28 20:27 UTC, nerdCopter commented
recommend setting your editor to auto-trim trailing spaces. and use 4-sapces for tabs automatically.

2024-02-28 20:42 UTC, demvlad commented
> recommend setting your editor to auto-trim trailing spaces. and use 4-sapces for tabs automatically.

Ok. I have 4-space auto.
But autotrim.. Thank's it is interest. Wiil find..

2024-02-29 07:27 UTC, demvlad commented
But i think that the warning about this situation must be at the main program window, it is not at internal spectrum chart only.

2024-03-01 22:33 UTC, haslinghuis commented on js/graph_spectrum_plot.js
> +};
```suggestion
};

```

2024-03-05 13:01 UTC, demvlad commented
The last changes improves issue, what i found on my Happymodel FC.
There are very big wrong RPM values  ever in the logs.
This improvement resolved this.

2024-03-05 17:59 UTC, haslinghuis requested changes
Did not check them all - as to minimize refactoring efforts.

2024-03-05 17:59 UTC, haslinghuis commented on js/graph_spectrum_plot.js
> +
:space_invader:

2024-03-05 17:59 UTC, haslinghuis commented on js/graph_spectrum_calc.js
> +
```suggestion
    if (this._BetaflightRate !== this._blackBoxRate) {
        return {
            actualRate: this._actualeRate,
            betaflightRate: this._BetaflightRate
        };
    }
    return undefined;
```

2024-03-05 17:59 UTC, haslinghuis commented on js/graph_spectrum.js
> +           this.resize = function() {
```suggestion
       this.resize = function() {
```

2024-03-05 20:06 UTC, haslinghuis commented on js/graph_spectrum_plot.js
> +
```suggestion
```

2024-03-05 20:44 UTC, haslinghuis commented on js/graph_spectrum_calc.js
> +            betaflightRate: this._BetaflightRate
```suggestion
            betaflightRate: this._BetaflightRate,
```

2024-03-05 20:45 UTC, haslinghuis approved these changes

2024-03-05 20:55 UTC, nerdCopter approved these changes
- approving based on conversations and still-working status with a few logs. did not deep-test.

2024-03-05 20:57 UTC, merged